-- ============================================
-- fix_dilewati_output.sql  (v2)
-- Generated by fix_dilewati.js
-- Jalankan di cPanel phpMyAdmin
-- ============================================

-- [TIDAK_DITEMUKAN] ---AHMAD HAIKAL ZIDAN AL-IKHSAN.jpg
-- QR: djAxr07UAAI02lLtEbJFfoQJ1R6+F71Am0bhIVUtuGgUzgIaaVNbpCxSe3EKrIgQJo8=

-- [TIDAK_DITEMUKAN] ---ALYCCIA ZANUBA ZAEIN.jpg
-- QR: djAx0wXVh65e/jhrkC+TmbC84XObhSw/OhDowN+a3d8LXC0Y0mWf7II3HsyJ1U/Qm9k=

-- [TIDAK_DITEMUKAN] ---ANDIENA NUR ANNISA FIRDAUSY.jpg
-- QR: djAxH9nBIJVbzn+GZQjV3Rl+dXZzE3nuck7wIMWgiuTN2nTlggNwbHwDudfLVK7AwDY=

-- [TIDAK_DITEMUKAN] ---ANGEL SABRINA RAMADHANI.jpg
-- QR: djAxDobQuc7FJk9LKaHRMY4Gc+TAU6SLEs5qtfya9NTvi1UYKBSEc6deL09s8wKGars=

-- [TIDAK_DITEMUKAN] ---ARDI DWI SETIA ANGGARA.jpg
-- QR: djAxDWfKha+RWjRjWRrqqWv0Kl2zpeERtDlbb94kmeTEgFavHkVHNHZj3xK44D0Yfpk=

-- [TIDAK_DITEMUKAN] ---ARINA NIDA AL QUDSIYAH.jpg
-- QR: djAxi9dTij3ODyVvme/1VxW2sRTeVeghUahW4rmQFAhEL8HUnhYoAWQRffr2Sb4OtHg=

-- [TIDAK_DITEMUKAN] ---AZRIL HARIS AL BANA.jpg
-- QR: djAxawFPlVyrhrbSKwa1HmZ7bWdf8ldeo/NKBX8blX8OTmjQD/AqWUy169blaBDQjk4=

-- [TIDAK_DITEMUKAN] ---BUNGA HIDAYATUS SHIYAM.jpg
-- QR: djAx2CNNyH/JSfcKXliHcExBSkVOI7Q8bXmfvyR+qSX3IyOEKBfsweaVfHwtBWeB2sU=

-- [TIDAK_DITEMUKAN] ---CITRA ALFINA WIDIANTO.jpg
-- QR: djAxG8mGa1QqEkr5KhBJnecxEhUC35VR72ZSGoOnN+V/pstjKlW25DcGhA6IwiKrNHo=

-- [TIDAK_DITEMUKAN] ---CITRA KIRANA LARASATI.jpg
-- QR: djAx/fgV7X4BVOPt2zDZvzFpmPR3W/PzfWkD1ZVWnz/bgtkHFtxBSc8zSNUAhGe9C58=

-- [MATCH-exact] ABD. ROUF WISNU WARDANA.jpg
-- Murid: ABD. RO`UF WISNU WARDANA (NIS: 2025070115) | QR: djAxcSP5Z26t18dCPRJ2bGGhCi+8FPOMgpRrAEvdOmkIj45Ku/qcXaDUDTpqIX1Pxn4=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxcSP5Z26t18dCPRJ2bGGhCi+8FPOMgpRrAEvdOmkIj45Ku/qcXaDUDTpqIX1Pxn4=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxcSP5Z26t18dCPRJ2bGGhCi+8FPOMgpRrAEvdOmkIj45Ku/qcXaDUDTpqIX1Pxn4=';
UPDATE murid SET barcode_id = 'djAxcSP5Z26t18dCPRJ2bGGhCi+8FPOMgpRrAEvdOmkIj45Ku/qcXaDUDTpqIX1Pxn4=' WHERE nis = '2025070115';

-- [MATCH-file-in-db] ABDULLOH FAQIH, M.AG.jpg
-- Guru: Agus H. Abdulloh Faqih (ID: 5) | QR: djAxjLBe6OmCaqEoDy1uJ/y8jbIu8H1ZKhAj/JPX3FjSNEVIL5Ilmtu6fvahUtD2MFk=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxjLBe6OmCaqEoDy1uJ/y8jbIu8H1ZKhAj/JPX3FjSNEVIL5Ilmtu6fvahUtD2MFk=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxjLBe6OmCaqEoDy1uJ/y8jbIu8H1ZKhAj/JPX3FjSNEVIL5Ilmtu6fvahUtD2MFk=';
UPDATE guru  SET barcode_id = 'djAxjLBe6OmCaqEoDy1uJ/y8jbIu8H1ZKhAj/JPX3FjSNEVIL5Ilmtu6fvahUtD2MFk=' WHERE guru_id = 5;

-- [TIDAK_DITEMUKAN] AFIFATUL ULYAH.jpg
-- QR: djAxaek9FUpR5QmdHWVNYKyySfztxTSLnoLRIy4oWk7ZSNvVOkriskMiVjPoSgnqGC8=

-- [TIDAK_DITEMUKAN] AHMAD FAIZAL REZA.jpg
-- QR: djAxbuIzlDMbNZKBjFCy/OY1FS+VWDtMuPkwbny9Yd1nxscC5JkzHd4yCWQtns2Sv8g=

-- [MATCH-exact] AHMAD FATIH HASAN AL-FARROS.jpg
-- Murid: AHMAD FATIH HASAN AL-FARROS (NIS: 2025070375) | QR: djAxHqw2FjmOHZLgr3ZFXbfq91sM5GZauUM/PKVtkX9DO6i0Bd/9wFRaY0IgmLtTlQk=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxHqw2FjmOHZLgr3ZFXbfq91sM5GZauUM/PKVtkX9DO6i0Bd/9wFRaY0IgmLtTlQk=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxHqw2FjmOHZLgr3ZFXbfq91sM5GZauUM/PKVtkX9DO6i0Bd/9wFRaY0IgmLtTlQk=';
UPDATE murid SET barcode_id = 'djAxHqw2FjmOHZLgr3ZFXbfq91sM5GZauUM/PKVtkX9DO6i0Bd/9wFRaY0IgmLtTlQk=' WHERE nis = '2025070375';

-- [TIDAK_DITEMUKAN] AHMAD IKMALUL FIKRI.jpg
-- QR: djAxYH/M/HX4JeEKOc8HRZbVL9PNfBSmh3uYgogS5SUqZ8nx5N7dGOMw/P1h6RmGvbU=

-- [TIDAK_DITEMUKAN] AHMAD NUR ATIQ.jpg
-- QR: djAxdhf8qeD+9MNqO+XBDc4Pi5Vpl8x5q9llAMMk6b8DTw0BlYluryePvkTqa5ZqnKw=

-- [TIDAK_DITEMUKAN] AHMAD SYARIF HIDAYATULLOH KHOIRUL IBAD.jpg
-- QR: djAxMngTnnRTa6X61eSq0o19VKwUtobWLS52sl0uH1s8P3LEXW6s0EieI4rwMgc9Tio=

-- [MATCH-exact] AINUR ZULFA AL-FARIKHAH.jpg
-- Murid: AINUR ZULFA AL-FARIKHAH (NIS: 2025070016) | QR: djAxYSlV0FAniNMdx2fXLw+Q2Ic049O0zXYignOlTKagyyWOZ2oClLBTxwVebwwURjc=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxYSlV0FAniNMdx2fXLw+Q2Ic049O0zXYignOlTKagyyWOZ2oClLBTxwVebwwURjc=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxYSlV0FAniNMdx2fXLw+Q2Ic049O0zXYignOlTKagyyWOZ2oClLBTxwVebwwURjc=';
UPDATE murid SET barcode_id = 'djAxYSlV0FAniNMdx2fXLw+Q2Ic049O0zXYignOlTKagyyWOZ2oClLBTxwVebwwURjc=' WHERE nis = '2025070016';

-- [MATCH-exact] AISYAH REGINA FAHMI AZ-ZAHRA.jpg
-- Murid: AISYAH REGINA FAHMI AZ-ZAHRA (NIS: 2025070331) | QR: djAx1FR875gsAdAww+Qpn8DW5VNmD/cGHODEE8JSY0IjTAEcs9SP+bBeBl1uHaCBfWg=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAx1FR875gsAdAww+Qpn8DW5VNmD/cGHODEE8JSY0IjTAEcs9SP+bBeBl1uHaCBfWg=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAx1FR875gsAdAww+Qpn8DW5VNmD/cGHODEE8JSY0IjTAEcs9SP+bBeBl1uHaCBfWg=';
UPDATE murid SET barcode_id = 'djAx1FR875gsAdAww+Qpn8DW5VNmD/cGHODEE8JSY0IjTAEcs9SP+bBeBl1uHaCBfWg=' WHERE nis = '2025070331';

-- [TIDAK_DITEMUKAN] AKHMAD ROFIDHUL ANA MAULANA.jpg
-- QR: djAxRQa3sTMKtsTuJYv1WbhIHM5yuXC6v1omKmVOFIOvSmvhOd9ftqF5UCnPALvDhgU=

-- [MATCH-file-in-db] ALMAS NABILAH AS SA`ADAH.jpg
-- Guru: Ustd. Almas Nabilah As Asaadah (ID: 123) | QR: djAxqX932mSKPrOUOiz7kPGGK8meaUxMByzEW0u/CEtbv0OTnyQPi+3/vzG3Z/Hm5rs=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxqX932mSKPrOUOiz7kPGGK8meaUxMByzEW0u/CEtbv0OTnyQPi+3/vzG3Z/Hm5rs=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxqX932mSKPrOUOiz7kPGGK8meaUxMByzEW0u/CEtbv0OTnyQPi+3/vzG3Z/Hm5rs=';
UPDATE guru  SET barcode_id = 'djAxqX932mSKPrOUOiz7kPGGK8meaUxMByzEW0u/CEtbv0OTnyQPi+3/vzG3Z/Hm5rs=' WHERE guru_id = 123;

-- [MATCH-exact] ALMIRA GHANIYAH AZ-ZAHRAH.jpg
-- Murid: ALMIRA GHANIYAH AZ-ZAHRAH (NIS: 2025070071) | QR: djAxR4ve2iPeVPnGNHKFJUzLGx/3KtxdWpcj+xAHKsCdlyC9UaHtN9xOulB2D0CRLoY=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxR4ve2iPeVPnGNHKFJUzLGx/3KtxdWpcj+xAHKsCdlyC9UaHtN9xOulB2D0CRLoY=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxR4ve2iPeVPnGNHKFJUzLGx/3KtxdWpcj+xAHKsCdlyC9UaHtN9xOulB2D0CRLoY=';
UPDATE murid SET barcode_id = 'djAxR4ve2iPeVPnGNHKFJUzLGx/3KtxdWpcj+xAHKsCdlyC9UaHtN9xOulB2D0CRLoY=' WHERE nis = '2025070071';

-- [TIDAK_DITEMUKAN] AMALIA ALFI KARROMALLAHU DAROJAT.jpg
-- QR: djAxv9k3bAu25qzAbA/9HNsu2fqWs4zNvaSQJugezEIBGFKJo36dubXv0HMw9A9kExs=

-- [TIDAK_DITEMUKAN] AMILATUL FITRIYAH.jpg
-- QR: djAxnqNcrj0YfXXUqyCItKQmVR5oNIn/iBFG5Cj09B6xAELvJxc2K38MlHBAus4+FlU=

-- [TIDAK_DITEMUKAN] ANINTIAS LAILI FIRDANA.jpg
-- QR: djAxx6wlsfwmIJhsrnHM5o4AuCwj39C1OHlZSX6y+A+VP5fxZ7W+49OnXIVTkrlkXJg=

-- [DUPLIKAT] ANISA RETNO LULUK NUR WAKISTASARI.jpg
-- Kemungkinan: Murid:ANISA RETNO LULUK NUR MANGGALI | Murid:ANITA RETNO LULUK NUR WAKISTASARI
-- QR: djAxPU/vN8Z2+x1ev5Rxj6K+ImKpFABqfqN+Bmxh5cbSdhFXV9rAg591sfpW9syyMZw=

-- [MATCH-db-in-file] ANNISA`ATUS SALAMIYAH.jpg
-- Guru: Ustd. Annisa\'atus Salamiyah (ID: 68) | QR: djAxOs15YK08Ph5TuWu1oOrn/Dt5WQ6ft1VNsIlZZhb5hGK8lQAB3fKmRMGU6H9lMl4=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxOs15YK08Ph5TuWu1oOrn/Dt5WQ6ft1VNsIlZZhb5hGK8lQAB3fKmRMGU6H9lMl4=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxOs15YK08Ph5TuWu1oOrn/Dt5WQ6ft1VNsIlZZhb5hGK8lQAB3fKmRMGU6H9lMl4=';
UPDATE guru  SET barcode_id = 'djAxOs15YK08Ph5TuWu1oOrn/Dt5WQ6ft1VNsIlZZhb5hGK8lQAB3fKmRMGU6H9lMl4=' WHERE guru_id = 68;

-- [MATCH-exact] ATINA FI QOLBY AS-SHOFA.jpg
-- Murid: ATINA FI QOLBY AS-SHOFA (NIS: 2025070044) | QR: djAxpzkjLBRQLNUVp5OmjIzegt7+3a87HAMG45xskz8XiiAMhJRkrp5sK5Y2yMojs7U=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxpzkjLBRQLNUVp5OmjIzegt7+3a87HAMG45xskz8XiiAMhJRkrp5sK5Y2yMojs7U=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxpzkjLBRQLNUVp5OmjIzegt7+3a87HAMG45xskz8XiiAMhJRkrp5sK5Y2yMojs7U=';
UPDATE murid SET barcode_id = 'djAxpzkjLBRQLNUVp5OmjIzegt7+3a87HAMG45xskz8XiiAMhJRkrp5sK5Y2yMojs7U=' WHERE nis = '2025070044';

-- [TIDAK_DITEMUKAN] AZKIYA ARIFATUL ABIDAH.jpg
-- QR: djAxdRO+uJKTIkAq1Mk/+VwWoM1FG4ez80WYxPjHC1gJBtemOAIQujldgktfA0LDGvk=

-- [TIDAK_DITEMUKAN] Copy of AHMAD AZKAL AISYI.jpg
-- QR: djAxh9iFCHXmEupHn82HXtqqbybcfq76xh9mX1wd/6QB9PPdxkGatJdXS9KlRm+8SNk=

-- [MATCH-exact] Copy of ALICYA RAHMADITA.jpg
-- Murid: ALICYA RAHMADITA (NIS: 2025070525) | QR: djAxAjoUP64T4AhxdcV/TdP4oKoSHeMvWQyLWUrw9EUjzlmQ1Ykz1yll+7243wV0YcI=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxAjoUP64T4AhxdcV/TdP4oKoSHeMvWQyLWUrw9EUjzlmQ1Ykz1yll+7243wV0YcI=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxAjoUP64T4AhxdcV/TdP4oKoSHeMvWQyLWUrw9EUjzlmQ1Ykz1yll+7243wV0YcI=';
UPDATE murid SET barcode_id = 'djAxAjoUP64T4AhxdcV/TdP4oKoSHeMvWQyLWUrw9EUjzlmQ1Ykz1yll+7243wV0YcI=' WHERE nis = '2025070525';

-- [MATCH-exact] Copy of ALYA KHAIRANI MAHFUDZ.jpg
-- Murid: ALYA KHAIRANI MAHFUDZ (NIS: 2025070630) | QR: djAx3jmz0UjC8Zf75WmXyz7sQolEqWK3CdxNfun/kj3u4YRPi0jExrxVHtJzxGTCXYU=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAx3jmz0UjC8Zf75WmXyz7sQolEqWK3CdxNfun/kj3u4YRPi0jExrxVHtJzxGTCXYU=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAx3jmz0UjC8Zf75WmXyz7sQolEqWK3CdxNfun/kj3u4YRPi0jExrxVHtJzxGTCXYU=';
UPDATE murid SET barcode_id = 'djAx3jmz0UjC8Zf75WmXyz7sQolEqWK3CdxNfun/kj3u4YRPi0jExrxVHtJzxGTCXYU=' WHERE nis = '2025070630';

-- [MATCH-file-in-db] Copy of ANDY HESTI.jpg
-- Murid: ANDY HESTI DALILIFAHIMA (NIS: 2024070219) | QR: djAxAQGPF6Mn76GevGfboI2zdhwiDmaNeDp7PGi9YK5jHUBe6basKx+Bj/v9RBKOEcU=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxAQGPF6Mn76GevGfboI2zdhwiDmaNeDp7PGi9YK5jHUBe6basKx+Bj/v9RBKOEcU=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxAQGPF6Mn76GevGfboI2zdhwiDmaNeDp7PGi9YK5jHUBe6basKx+Bj/v9RBKOEcU=';
UPDATE murid SET barcode_id = 'djAxAQGPF6Mn76GevGfboI2zdhwiDmaNeDp7PGi9YK5jHUBe6basKx+Bj/v9RBKOEcU=' WHERE nis = '2024070219';

-- [MATCH-exact] Copy of AUREL NUR HABIBATUL LATHIFAH.jpg
-- Murid: AUREL NUR HABIBATUL LATHIFAH (NIS: 2024070498) | QR: djAx2S7+hKwoSSu7tDkpmpdDprq/rI1aW141R6W9Ja5Mlg3cTU3cH3RQRFgO4VQfD2Y=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAx2S7+hKwoSSu7tDkpmpdDprq/rI1aW141R6W9Ja5Mlg3cTU3cH3RQRFgO4VQfD2Y=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAx2S7+hKwoSSu7tDkpmpdDprq/rI1aW141R6W9Ja5Mlg3cTU3cH3RQRFgO4VQfD2Y=';
UPDATE murid SET barcode_id = 'djAx2S7+hKwoSSu7tDkpmpdDprq/rI1aW141R6W9Ja5Mlg3cTU3cH3RQRFgO4VQfD2Y=' WHERE nis = '2024070498';

-- [MATCH-exact] Copy of ELOK FAIQOH.jpg
-- Murid: ELOK FAIQOH (NIS: 2025070278) | QR: djAxikmZJ64Jg6QC74SF5++uM8IsoMYcXHBMF11LtBBd6jlkiSZi08Nn3U+lkvVRfqg=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxikmZJ64Jg6QC74SF5++uM8IsoMYcXHBMF11LtBBd6jlkiSZi08Nn3U+lkvVRfqg=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxikmZJ64Jg6QC74SF5++uM8IsoMYcXHBMF11LtBBd6jlkiSZi08Nn3U+lkvVRfqg=';
UPDATE murid SET barcode_id = 'djAxikmZJ64Jg6QC74SF5++uM8IsoMYcXHBMF11LtBBd6jlkiSZi08Nn3U+lkvVRfqg=' WHERE nis = '2025070278';

-- [MATCH-db-in-file] Copy of ISYTIDZIL KARIMAH.jpg
-- Murid: ISYTI DZIL KARIMAH (NIS: 2024070465) | QR: djAx9atgqm1GKKoVU5ATwCn71RR66E+IIj8OHig8KMozrOqpqJCvw/vV/YOM30hhz5g=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAx9atgqm1GKKoVU5ATwCn71RR66E+IIj8OHig8KMozrOqpqJCvw/vV/YOM30hhz5g=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAx9atgqm1GKKoVU5ATwCn71RR66E+IIj8OHig8KMozrOqpqJCvw/vV/YOM30hhz5g=';
UPDATE murid SET barcode_id = 'djAx9atgqm1GKKoVU5ATwCn71RR66E+IIj8OHig8KMozrOqpqJCvw/vV/YOM30hhz5g=' WHERE nis = '2024070465';

-- [MATCH-exact] Copy of KANZA DINA AQWIYA.jpg
-- Murid: KANZA DINA AQWIYA (NIS: 2024070012) | QR: djAxHgkCqFWPq0ZsDH4cCx0xwumrMoiMy0L6xHmercj8FAKld4D+ZcMJjfMz5zcPYPU=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxHgkCqFWPq0ZsDH4cCx0xwumrMoiMy0L6xHmercj8FAKld4D+ZcMJjfMz5zcPYPU=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxHgkCqFWPq0ZsDH4cCx0xwumrMoiMy0L6xHmercj8FAKld4D+ZcMJjfMz5zcPYPU=';
UPDATE murid SET barcode_id = 'djAxHgkCqFWPq0ZsDH4cCx0xwumrMoiMy0L6xHmercj8FAKld4D+ZcMJjfMz5zcPYPU=' WHERE nis = '2024070012';

-- [MATCH-exact] Copy of KHAIRANI PUTRI ANGGRAINI (1).jpg
-- Murid: KHAIRANI PUTRI ANGGRAINI (NIS: 2024070013) | QR: djAx5PLBLHu96hC7NqJkoh2qoibWhJcZE2S0mFLuzpss1x6gYin0W2L0MPE=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAx5PLBLHu96hC7NqJkoh2qoibWhJcZE2S0mFLuzpss1x6gYin0W2L0MPE=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAx5PLBLHu96hC7NqJkoh2qoibWhJcZE2S0mFLuzpss1x6gYin0W2L0MPE=';
UPDATE murid SET barcode_id = 'djAx5PLBLHu96hC7NqJkoh2qoibWhJcZE2S0mFLuzpss1x6gYin0W2L0MPE=' WHERE nis = '2024070013';

-- [MATCH-exact] Copy of MEIRZA TRISNA DWI ANDINI.jpg
-- Murid: MEIRZA TRISNA DWI ANDINI (NIS: 2024070732) | QR: djAx7iKiaP8MjIlDAjRb2R/GXNeuqCl3ID9bLx6uWRXuRhuFBJ/cJZRMN99jFQWeqZQ=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAx7iKiaP8MjIlDAjRb2R/GXNeuqCl3ID9bLx6uWRXuRhuFBJ/cJZRMN99jFQWeqZQ=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAx7iKiaP8MjIlDAjRb2R/GXNeuqCl3ID9bLx6uWRXuRhuFBJ/cJZRMN99jFQWeqZQ=';
UPDATE murid SET barcode_id = 'djAx7iKiaP8MjIlDAjRb2R/GXNeuqCl3ID9bLx6uWRXuRhuFBJ/cJZRMN99jFQWeqZQ=' WHERE nis = '2024070732';

-- [MATCH-exact] Copy of MUTIARA AZZAHRA.jpg
-- Murid: MUTIARA AZZAHRA (NIS: 2024070562) | QR: djAxjbUQp3HpGvq9WV5jy5u3dTbQJDmcnNY/+X9TdsQdeuavRuaD7CD/9SSLk5E+z04=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxjbUQp3HpGvq9WV5jy5u3dTbQJDmcnNY/+X9TdsQdeuavRuaD7CD/9SSLk5E+z04=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxjbUQp3HpGvq9WV5jy5u3dTbQJDmcnNY/+X9TdsQdeuavRuaD7CD/9SSLk5E+z04=';
UPDATE murid SET barcode_id = 'djAxjbUQp3HpGvq9WV5jy5u3dTbQJDmcnNY/+X9TdsQdeuavRuaD7CD/9SSLk5E+z04=' WHERE nis = '2024070562';

-- [MATCH-exact] Copy of NAFISA BARROTUS TSANIAH.jpg
-- Murid: NAFISA BARROTUS TSANIAH (NIS: 2024070018) | QR: djAxLX8P93N0wUmQrxqhIu81VBDkDHfLUxjAjX9xfZPPtK04wYf+VP0X9isYMBHjIhs=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxLX8P93N0wUmQrxqhIu81VBDkDHfLUxjAjX9xfZPPtK04wYf+VP0X9isYMBHjIhs=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxLX8P93N0wUmQrxqhIu81VBDkDHfLUxjAjX9xfZPPtK04wYf+VP0X9isYMBHjIhs=';
UPDATE murid SET barcode_id = 'djAxLX8P93N0wUmQrxqhIu81VBDkDHfLUxjAjX9xfZPPtK04wYf+VP0X9isYMBHjIhs=' WHERE nis = '2024070018';

-- [TIDAK_DITEMUKAN] Copy of NUR IZZAH SYARIFAH.jpg
-- QR: djAxUV03OoFrUtci957PiHrJtFmvf1r6o4upl22pnrkburyv6/Brn4dKEw/3284FT8M=

-- [MATCH-exact] Copy of RAISA PUTRI ELYSIA SADIRA.jpg
-- Murid: RAISA PUTRI ELYSIA SADIRA (NIS: 2024070750) | QR: djAxgeTW5TbzdDHhyL7mlu4i3zZYukTMfij3bqfc6nqvQy4QCGr1iIiXTdXWA1lx8Bc=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxgeTW5TbzdDHhyL7mlu4i3zZYukTMfij3bqfc6nqvQy4QCGr1iIiXTdXWA1lx8Bc=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxgeTW5TbzdDHhyL7mlu4i3zZYukTMfij3bqfc6nqvQy4QCGr1iIiXTdXWA1lx8Bc=';
UPDATE murid SET barcode_id = 'djAxgeTW5TbzdDHhyL7mlu4i3zZYukTMfij3bqfc6nqvQy4QCGr1iIiXTdXWA1lx8Bc=' WHERE nis = '2024070750';

-- [MATCH-exact] Copy of SHIELLAH ALFI ALKARIMAH YUSUF.jpg
-- Murid: SHIELLAH ALFI ALKARIMAH YUSUF (NIS: 2024070023) | QR: djAxYQPhjm6S/VGwNUErJwemWvFVFvdH7yR4y4wNeWHQZVWqK7ia0XgcQ7T3MW5jnl0=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxYQPhjm6S/VGwNUErJwemWvFVFvdH7yR4y4wNeWHQZVWqK7ia0XgcQ7T3MW5jnl0=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxYQPhjm6S/VGwNUErJwemWvFVFvdH7yR4y4wNeWHQZVWqK7ia0XgcQ7T3MW5jnl0=';
UPDATE murid SET barcode_id = 'djAxYQPhjm6S/VGwNUErJwemWvFVFvdH7yR4y4wNeWHQZVWqK7ia0XgcQ7T3MW5jnl0=' WHERE nis = '2024070023';

-- [MATCH-exact] Copy of SYARIFATUL ULEM AZ ZUMY.jpg
-- Murid: SYARIFATUL ULEM AZ ZUMY (NIS: 2025070361) | QR: djAxFORgyrz+ZOqI7p+9JRVlCc9B8/EGXrR2BvElo6o6Qq8vhftLuonsm/Cd/bp32qA=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxFORgyrz+ZOqI7p+9JRVlCc9B8/EGXrR2BvElo6o6Qq8vhftLuonsm/Cd/bp32qA=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxFORgyrz+ZOqI7p+9JRVlCc9B8/EGXrR2BvElo6o6Qq8vhftLuonsm/Cd/bp32qA=';
UPDATE murid SET barcode_id = 'djAxFORgyrz+ZOqI7p+9JRVlCc9B8/EGXrR2BvElo6o6Qq8vhftLuonsm/Cd/bp32qA=' WHERE nis = '2025070361';

-- [MATCH-exact] Copy of WAHYUNI SUCI RAHMADANI.jpg
-- Murid: WAHYUNI SUCI RAHMADANI (NIS: 2024070731) | QR: djAx+1Id/O0QrYuj2X+O/hFoYrOHhY3ZBemPJt/CA0RlC1r2BYzyXi37do/piwKJ+3k=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAx+1Id/O0QrYuj2X+O/hFoYrOHhY3ZBemPJt/CA0RlC1r2BYzyXi37do/piwKJ+3k=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAx+1Id/O0QrYuj2X+O/hFoYrOHhY3ZBemPJt/CA0RlC1r2BYzyXi37do/piwKJ+3k=';
UPDATE murid SET barcode_id = 'djAx+1Id/O0QrYuj2X+O/hFoYrOHhY3ZBemPJt/CA0RlC1r2BYzyXi37do/piwKJ+3k=' WHERE nis = '2024070731';

-- [MATCH-exact] Copy of ZAHRA RISKI ALFIANA.jpg
-- Murid: ZAHRA RISKI ALFIANA (NIS: 2024070733) | QR: djAxj4KKiGncA5t6p5BvqB99an+citYI8dcRRfqjhbfjMrirghQskimSKA+gerBPvN0=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxj4KKiGncA5t6p5BvqB99an+citYI8dcRRfqjhbfjMrirghQskimSKA+gerBPvN0=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxj4KKiGncA5t6p5BvqB99an+citYI8dcRRfqjhbfjMrirghQskimSKA+gerBPvN0=';
UPDATE murid SET barcode_id = 'djAxj4KKiGncA5t6p5BvqB99an+citYI8dcRRfqjhbfjMrirghQskimSKA+gerBPvN0=' WHERE nis = '2024070733';

-- [MATCH-exact] Copy of ZETTY FITRIANI AFIDAH.jpg
-- Murid: ZETTY FITRIANI AFIDAH (NIS: 2025070508) | QR: djAx2PAc5vW8JIQ51IFNsAIA5/xzPYSyssBTRhJnc9GDbKelhrn6CPWH4EXcqEppeOE=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAx2PAc5vW8JIQ51IFNsAIA5/xzPYSyssBTRhJnc9GDbKelhrn6CPWH4EXcqEppeOE=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAx2PAc5vW8JIQ51IFNsAIA5/xzPYSyssBTRhJnc9GDbKelhrn6CPWH4EXcqEppeOE=';
UPDATE murid SET barcode_id = 'djAx2PAc5vW8JIQ51IFNsAIA5/xzPYSyssBTRhJnc9GDbKelhrn6CPWH4EXcqEppeOE=' WHERE nis = '2025070508';

-- [MATCH-file-in-db] DEWI BADRIYAH AT TAMAMATUZ ZAHROH.jpg
-- Guru: Ustd. Dewi Badriyah Attamamatuz Zahroh (ID: 82) | QR: djAxosAn/ES3t01oXhCZpMiNE7ELvSSl9V+Nfqcc5kugb8bowt78Vym8CIYpIgsxioA=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxosAn/ES3t01oXhCZpMiNE7ELvSSl9V+Nfqcc5kugb8bowt78Vym8CIYpIgsxioA=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxosAn/ES3t01oXhCZpMiNE7ELvSSl9V+Nfqcc5kugb8bowt78Vym8CIYpIgsxioA=';
UPDATE guru  SET barcode_id = 'djAxosAn/ES3t01oXhCZpMiNE7ELvSSl9V+Nfqcc5kugb8bowt78Vym8CIYpIgsxioA=' WHERE guru_id = 82;

-- [MATCH-db-in-file] DEWI RETNOSARI.jpg
-- Guru: Ustd. Dewi retno sari (ID: 67) | QR: djAxLynDUN+YXQbTFDIVp2gv8oB7gfIWl7e/+7fvUFy4Oj+Ew8JQNQKsDLaLJCFzq8Q=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxLynDUN+YXQbTFDIVp2gv8oB7gfIWl7e/+7fvUFy4Oj+Ew8JQNQKsDLaLJCFzq8Q=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxLynDUN+YXQbTFDIVp2gv8oB7gfIWl7e/+7fvUFy4Oj+Ew8JQNQKsDLaLJCFzq8Q=';
UPDATE guru  SET barcode_id = 'djAxLynDUN+YXQbTFDIVp2gv8oB7gfIWl7e/+7fvUFy4Oj+Ew8JQNQKsDLaLJCFzq8Q=' WHERE guru_id = 67;

-- [TIDAK_DITEMUKAN] DIAZ RIZQI SAPUTRA.jpg
-- QR: djAxa2ONrAsyUouG06/G9iAS17FgGsTi/WdPw1MLENRgayV3VaVa/G6WM42B7OTuAYM=

-- [MATCH-db-in-file] DRA. HJ. KHOTIMAH SURYANI, M.AG.jpg
-- Guru: Hj. Khotimah Suryani (ID: 58) | QR: djAxZxvJN6dsBLLIU7FS+xv1L3p+BcuR0rb19aG2leySTr8xpIZ4HtCkEKp3iwzv0Sk=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxZxvJN6dsBLLIU7FS+xv1L3p+BcuR0rb19aG2leySTr8xpIZ4HtCkEKp3iwzv0Sk=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxZxvJN6dsBLLIU7FS+xv1L3p+BcuR0rb19aG2leySTr8xpIZ4HtCkEKp3iwzv0Sk=';
UPDATE guru  SET barcode_id = 'djAxZxvJN6dsBLLIU7FS+xv1L3p+BcuR0rb19aG2leySTr8xpIZ4HtCkEKp3iwzv0Sk=' WHERE guru_id = 58;

-- [MATCH-exact] DRS. MUHID, M.AG.jpg
-- Guru: KH. Muhid (ID: 2) | QR: djAxG3GFZPZ7rWva9AaqP8crBgQk8tlfjpTrjKNJFHQ2U8wZpOgqtne6SzildfUyh58=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxG3GFZPZ7rWva9AaqP8crBgQk8tlfjpTrjKNJFHQ2U8wZpOgqtne6SzildfUyh58=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxG3GFZPZ7rWva9AaqP8crBgQk8tlfjpTrjKNJFHQ2U8wZpOgqtne6SzildfUyh58=';
UPDATE guru  SET barcode_id = 'djAxG3GFZPZ7rWva9AaqP8crBgQk8tlfjpTrjKNJFHQ2U8wZpOgqtne6SzildfUyh58=' WHERE guru_id = 2;

-- [TIDAK_DITEMUKAN] DZUN NUHA MAHMUDAH.jpg
-- QR: djAxyP1Cw+q7cr+k1nb3qk1M17x+N+Fa6zsYhUo0c+kw1oha+7tEqXgREWfQh9Q534E=

-- [MATCH-db-in-file] ELISAH NOVI LATHIFAH.jpg
-- Guru: Ustd. Elisa Novi Lathifah (ID: 121) | QR: djAxpChW0+OnKlMFr528LmWs17rjHS7A3VlRAa0QA1qzL6Mn9Y8o48mAhIztJRcocf0=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxpChW0+OnKlMFr528LmWs17rjHS7A3VlRAa0QA1qzL6Mn9Y8o48mAhIztJRcocf0=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxpChW0+OnKlMFr528LmWs17rjHS7A3VlRAa0QA1qzL6Mn9Y8o48mAhIztJRcocf0=';
UPDATE guru  SET barcode_id = 'djAxpChW0+OnKlMFr528LmWs17rjHS7A3VlRAa0QA1qzL6Mn9Y8o48mAhIztJRcocf0=' WHERE guru_id = 121;

-- [TIDAK_DITEMUKAN] ERFINA TRIANGGRAINI.jpg
-- QR: djAx/LGpzC1G+ntIIjHwRQCpYoYGuwZBzI5uDTlVnBOwqazzF8aJVJmrkelAuCNdhOg=

-- [TIDAK_DITEMUKAN] ERNA MASTININGRUM.jpg
-- QR: djAxAlG/8WQ72mw/pzOipahz+iR8goZt99IZkUmRQmaZ52/glhZ36nYjpyYMAmFjo5Q=

-- [TIDAK_DITEMUKAN] FANI NUR AFIFAH.jpg
-- QR: djAx6YZ3I/loZ0HkNRL3oliEn+oNlyyEffO6JqcdhP5VMv/q376gLp2SJMscX//rSew=

-- [MATCH-exact] FARIHA HANIF AZ-ZAHRA.jpg
-- Murid: FARIHA HANIF AZ-ZAHRA (NIS: 2025070154) | QR: djAxVz7YHlKzbhL+9dlBqQSDK0S2zBo5RxH03sihN9mzS1lcnsOIo1yq2uiFGKk8lgM=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxVz7YHlKzbhL+9dlBqQSDK0S2zBo5RxH03sihN9mzS1lcnsOIo1yq2uiFGKk8lgM=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxVz7YHlKzbhL+9dlBqQSDK0S2zBo5RxH03sihN9mzS1lcnsOIo1yq2uiFGKk8lgM=';
UPDATE murid SET barcode_id = 'djAxVz7YHlKzbhL+9dlBqQSDK0S2zBo5RxH03sihN9mzS1lcnsOIo1yq2uiFGKk8lgM=' WHERE nis = '2025070154';

-- [TIDAK_DITEMUKAN] FATIKH AFAN KURNIAWAN.jpg
-- QR: djAxGGcl5j00tdHUPAQgEzz459I5K+bfTKEayMyqc3g6FNEn3Va4bn4elcryKf8qCWU=

-- [TIDAK_DITEMUKAN] FEBILLA PUTRI.jpg
-- QR: djAx2oqXNAAzqe47NOp2eMQU5j6hzy7BQ2E1mq/VfGZNGPSnHi/KdTmqJIYaueuvBZc=

-- [MATCH-db-in-file] FEBY AYU MUDASARI.jpg
-- Guru: Ustd. Feby Ayu Muda Sari (ID: 93) | QR: djAxIQwHOt3MQbqziStF+vZ4GXQl1emXqSbghD61+uDvy4bzJdjhOYA+AQat3WOJqyU=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxIQwHOt3MQbqziStF+vZ4GXQl1emXqSbghD61+uDvy4bzJdjhOYA+AQat3WOJqyU=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxIQwHOt3MQbqziStF+vZ4GXQl1emXqSbghD61+uDvy4bzJdjhOYA+AQat3WOJqyU=';
UPDATE guru  SET barcode_id = 'djAxIQwHOt3MQbqziStF+vZ4GXQl1emXqSbghD61+uDvy4bzJdjhOYA+AQat3WOJqyU=' WHERE guru_id = 93;

-- [TIDAK_DITEMUKAN] FITHRUNNADA.jpg
-- QR: djAxHOJBKP6gnloxJx0CgCg2gfBN3ixLzCZQdd0hxDJDnQDIqdDVxxhmDlquwOxuKdg=

-- [MATCH-file-in-db] GHINA ANIFAH KHOIRUN NISA.jpg
-- Guru: Ustd. Ghina Anifah Khoirun Anisa (ID: 127) | QR: djAxZH1joUSXn8Lm52i3KVkAGDOK1q6yWPAGX1qtoC9j6jf3GITh+ZUyhl5VXf+2wM0=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxZH1joUSXn8Lm52i3KVkAGDOK1q6yWPAGX1qtoC9j6jf3GITh+ZUyhl5VXf+2wM0=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxZH1joUSXn8Lm52i3KVkAGDOK1q6yWPAGX1qtoC9j6jf3GITh+ZUyhl5VXf+2wM0=';
UPDATE guru  SET barcode_id = 'djAxZH1joUSXn8Lm52i3KVkAGDOK1q6yWPAGX1qtoC9j6jf3GITh+ZUyhl5VXf+2wM0=' WHERE guru_id = 127;

-- [TIDAK_DITEMUKAN] GILANG SETYO PRATOMO.jpg
-- QR: djAxYvggK5+kqmvCuU5UjEywcRerk7pQyzPpdJgHqBrCxs4rdlsOu909oW6xcMJZ1/8=

-- [TIDAK_DITEMUKAN] H. ALI MUSTAIN, DRS.jpg
-- QR: djAxcbBwuKOhZKY/TorpcVFdNQQJfDVZ/8AQ7aeDgTZBuBQNcgCL9m3vPwUbSCHpWiU=

-- [TIDAK_DITEMUKAN] HALIMATUS SA`ADAH.jpg
-- QR: djAxHGwbbewjmX0KLj+oGfGB7xL9iYq5GN4mT6nJIktbzSiBHMTUBoCX8FbEtfP3FO0=

-- [TIDAK_DITEMUKAN] HENIS INSYIROTUL AZIIDAH.jpg
-- QR: djAxICfjwMHj7kQxD8J6P5r+g6Pg1xYoX7tW3dbdpHVJdzxrSQOQOi7FafnnaxQtw4Q=

-- [TIDAK_DITEMUKAN] HJ. SHOFIJAH.jpg
-- QR: djAxrrr0AhioybLJyshklR96OxyzUCccFjUI5//h7S4go0VgaX9g4BuGVmtUqAJqMxE=

-- [TIDAK_DITEMUKAN] HJ. ZAENAB.jpg
-- QR: djAxpOGuL4yDBb8hf/dVzVt/iJ7J82dvWCbtoqYCIMpnZeNMHM9JPfE2gO8Kf18Jv1g=

-- [MATCH-db-in-file] IBRIZAH MAJIDAH.jpg
-- Guru: Ustd. Ibriza Majidah (ID: 75) | QR: djAxi/pQYseiypRWnhYLGYFzlWqgnqZw6zOnlu07tbvRiRFve9kcoIloWWww/ysaTBI=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxi/pQYseiypRWnhYLGYFzlWqgnqZw6zOnlu07tbvRiRFve9kcoIloWWww/ysaTBI=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxi/pQYseiypRWnhYLGYFzlWqgnqZw6zOnlu07tbvRiRFve9kcoIloWWww/ysaTBI=';
UPDATE guru  SET barcode_id = 'djAxi/pQYseiypRWnhYLGYFzlWqgnqZw6zOnlu07tbvRiRFve9kcoIloWWww/ysaTBI=' WHERE guru_id = 75;

-- [TIDAK_DITEMUKAN] IFATUR ROHMAH.jpg
-- QR: djAxcroO2dMWFmfnX6q2tUNFJHbkOQmkvay/IBIZGcSQKpXqRbcIHdFWoqbtZ1ocP0A=

-- [TIDAK_DITEMUKAN] JOKO NURSIYO, M.HI.jpg
-- QR: djAxrwTZaE/7NmCrPL5RomR9zpuGbEcRKiiLKFemLur16zgURWLeMPryJisfDL8O6gk=

-- [MATCH-exact] JOVANKA ALIFFATUZ ZAM-ZAMI.jpg
-- Murid: JOVANKA ALIFFATUZ ZAM-ZAMI (NIS: 2025070267) | QR: djAx4FNnDoN5+sDq8mYcW4ZsqAdGPiJ3m+XS627GKTz0CnstagaLZkLrsobQhqSNCUg=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAx4FNnDoN5+sDq8mYcW4ZsqAdGPiJ3m+XS627GKTz0CnstagaLZkLrsobQhqSNCUg=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAx4FNnDoN5+sDq8mYcW4ZsqAdGPiJ3m+XS627GKTz0CnstagaLZkLrsobQhqSNCUg=';
UPDATE murid SET barcode_id = 'djAx4FNnDoN5+sDq8mYcW4ZsqAdGPiJ3m+XS627GKTz0CnstagaLZkLrsobQhqSNCUg=' WHERE nis = '2025070267';

-- [TIDAK_DITEMUKAN] KARISMA KHOIRUNISA R.jpg
-- QR: djAxv7WT7/KWn7CtFGoDLJP9Q438/ouzQAAhacjzvO9BtMAZnXUpqFJQNr+Zwg/Hgwg=

-- [TIDAK_DITEMUKAN] KHOMSATUN.jpg
-- QR: djAxBrdfIsqD1A8YaXLjGIXs1w2tx9SafaLfUGZUwIwvLpY2rnyCsyyUOLL0Wl1OmJE=

-- [MATCH-file-in-db] KHUMAIRO SYARIFAH.jpg
-- Guru: Ustd. Khumairoh Syarifah (ID: 89) | QR: djAxWzqJbzjx8JgT8s5CAndiU9DvxBIo9s8tAN3kQJ5R3mrx0WrY+xcVuXXe+5XTLCM=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxWzqJbzjx8JgT8s5CAndiU9DvxBIo9s8tAN3kQJ5R3mrx0WrY+xcVuXXe+5XTLCM=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxWzqJbzjx8JgT8s5CAndiU9DvxBIo9s8tAN3kQJ5R3mrx0WrY+xcVuXXe+5XTLCM=';
UPDATE guru  SET barcode_id = 'djAxWzqJbzjx8JgT8s5CAndiU9DvxBIo9s8tAN3kQJ5R3mrx0WrY+xcVuXXe+5XTLCM=' WHERE guru_id = 89;

-- [MATCH-exact] LAELATUL ISRO`IYAH.jpg
-- Guru: Ustd. Laelatul Isroiyah (ID: 74) | QR: djAx7UTkzT94WOfqeTev1oETPdp6vE/7pqkQTKZh30+H+VZLuBWh0oWSVAcWFau2J+8=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAx7UTkzT94WOfqeTev1oETPdp6vE/7pqkQTKZh30+H+VZLuBWh0oWSVAcWFau2J+8=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAx7UTkzT94WOfqeTev1oETPdp6vE/7pqkQTKZh30+H+VZLuBWh0oWSVAcWFau2J+8=';
UPDATE guru  SET barcode_id = 'djAx7UTkzT94WOfqeTev1oETPdp6vE/7pqkQTKZh30+H+VZLuBWh0oWSVAcWFau2J+8=' WHERE guru_id = 74;

-- [MATCH-exact] LAILATUL KHUSNA__ (1).jpg
-- Murid: LAILATUL KHUSNA (NIS: 2025070356) | QR: djAxWE/aaiUczuQU+NtGFiLFh9l8npebVAPOpBISpctUKUyB7+YmNkYqVfpIAtgU6L0=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxWE/aaiUczuQU+NtGFiLFh9l8npebVAPOpBISpctUKUyB7+YmNkYqVfpIAtgU6L0=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxWE/aaiUczuQU+NtGFiLFh9l8npebVAPOpBISpctUKUyB7+YmNkYqVfpIAtgU6L0=';
UPDATE murid SET barcode_id = 'djAxWE/aaiUczuQU+NtGFiLFh9l8npebVAPOpBISpctUKUyB7+YmNkYqVfpIAtgU6L0=' WHERE nis = '2025070356';

-- [TIDAK_DITEMUKAN] LATIFATUL AINIYAH.jpg
-- QR: djAxuaAmWPNs9xTBYBHSQnd8WyUS5tR0bsIwKuSLLySElohvVBe6BcaXzfLQlufYOH8=

-- [TIDAK_DITEMUKAN] M NAQOUIB ASHROFUN NASHR.jpg
-- QR: djAxEQfzIkNg91InsKmhhVI6IHLHkY9ernLSBaPgR7QdR40bMqARB4RFP2ZjYH91oFQ=

-- [TIDAK_DITEMUKAN] M. AFIF HASBULLAH.jpg
-- QR: djAxJrYMWhIdUxWS+ORnVIQKgTZs/5fp4EI5UrX6jp/E3PbWKUZkaxDV8Kw87HtbNS8=

-- [TIDAK_DITEMUKAN] M. FIRZA MAULANA IBAADURROHMAN.jpg
-- QR: djAxjxxOt+Z06nuIc9FLcbBcum5Jjpo4JTFKmRAif5k575p8PrzrFcCJGj1BTW9N1RA=

-- [TIDAK_DITEMUKAN] M. IZAM MARFIANSYAH.jpg
-- QR: djAx6q96IyzC/CHxY9CN8jKPpyJgpDmCW97bijEPu+AWkRyOv5H+58QszcoUWZHv5dM=

-- [MATCH-file-in-db] M. MAHBUB JUNAIDI.jpg
-- Guru: Ust. Mahbub Junaidi (ID: 53) | QR: djAxVRaxHDcXQwmvC95uq2FPsWnQ+hW9/4TWgkM2msNgPjpu+oa6DuR6ORX11qJIt64=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxVRaxHDcXQwmvC95uq2FPsWnQ+hW9/4TWgkM2msNgPjpu+oa6DuR6ORX11qJIt64=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxVRaxHDcXQwmvC95uq2FPsWnQ+hW9/4TWgkM2msNgPjpu+oa6DuR6ORX11qJIt64=';
UPDATE guru  SET barcode_id = 'djAxVRaxHDcXQwmvC95uq2FPsWnQ+hW9/4TWgkM2msNgPjpu+oa6DuR6ORX11qJIt64=' WHERE guru_id = 53;

-- [TIDAK_DITEMUKAN] MARATUS SHOLIHAH.jpg
-- QR: djAxF3eT8PwfFfdgxgBp7zBlvJrp/PB66CPhWPDSHFkMsKkyQpX4PaAilRaT77vm9eY=

-- [TIDAK_DITEMUKAN] MAZIDATUL MUTIAH.jpg
-- QR: djAxBVVz6wxXyFs96dGt/40usDLBe+kXVmo1mpSFxuagAlcue1Vylg/WQqZG/nZa9+w=

-- [MATCH-db-in-file] MEISYA JUWITA SARI.jpg
-- Murid: MEISY JUWITA SARI (NIS: 2025070526) | QR: djAxHL0N6PiS9hD4fuTaLPAOXiUXAk44eOcL4TleopRbMLjYeMlNJZvtkGMbh2OCC68=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxHL0N6PiS9hD4fuTaLPAOXiUXAk44eOcL4TleopRbMLjYeMlNJZvtkGMbh2OCC68=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxHL0N6PiS9hD4fuTaLPAOXiUXAk44eOcL4TleopRbMLjYeMlNJZvtkGMbh2OCC68=';
UPDATE murid SET barcode_id = 'djAxHL0N6PiS9hD4fuTaLPAOXiUXAk44eOcL4TleopRbMLjYeMlNJZvtkGMbh2OCC68=' WHERE nis = '2025070526';

-- [MATCH-exact] MOH. HAZIQ ISYRAQ EL-QORI.jpg
-- Murid: MOH. HAZIQ ISYRAQ EL-QORI (NIS: 2025070365) | QR: djAxDCTPej01ebYyrirWPhvAqNZ8dTNlJKz9jm/W23G3ZKI/XCa1JD+jVV44NITzG2M=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxDCTPej01ebYyrirWPhvAqNZ8dTNlJKz9jm/W23G3ZKI/XCa1JD+jVV44NITzG2M=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxDCTPej01ebYyrirWPhvAqNZ8dTNlJKz9jm/W23G3ZKI/XCa1JD+jVV44NITzG2M=';
UPDATE murid SET barcode_id = 'djAxDCTPej01ebYyrirWPhvAqNZ8dTNlJKz9jm/W23G3ZKI/XCa1JD+jVV44NITzG2M=' WHERE nis = '2025070365';

-- [TIDAK_DITEMUKAN] MOH. SAIFULLOH.jpg
-- QR: djAxLbyUjRHBxAi2wjnXmMIJtyfbOWv7xlDrueW94mAYj7sKu1dxD4TapdETwoMwaOw=

-- [TIDAK_DITEMUKAN] MOH. SYAFIQ SUFYAN KHOIRUR R.jpg
-- QR: djAxHeD+YIq1TZYlO2Ke2ZbDEUD6TL0YaxQC0PROAtSpoHZSvxs5+vHPyRPvRUqZoQg=

-- [TIDAK_DITEMUKAN] MOHAMMAD RIZKY JOSINO.jpg
-- QR: djAxnkNXJROxCKGAeHDIcxGmvIc35NNmqnCV39eLWkEOgQnU2vUTXGdMLyykbN/spDE=

-- [TIDAK_DITEMUKAN] MOHAMMAD SYAIFULLAH ABID.jpg
-- QR: djAxBfFzw+0D12pwWCJ9aX5loKzgvufJdEeJqV8kbGy6RHaPhxgXHA/kavw+/em/t0Q=

-- [MATCH-db-in-file] MUFIDATUL MUNAWAROH, S.PSI..jpg
-- Guru: Hj. Mufidatul Munawaroh (ID: 61) | QR: djAx3tJM7pEN2lLhsrFOAzCEzMncfj4mngZmlB9n5EfMZxvGg7OlNhU6EJ7qbB6TiqY=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAx3tJM7pEN2lLhsrFOAzCEzMncfj4mngZmlB9n5EfMZxvGg7OlNhU6EJ7qbB6TiqY=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAx3tJM7pEN2lLhsrFOAzCEzMncfj4mngZmlB9n5EfMZxvGg7OlNhU6EJ7qbB6TiqY=';
UPDATE guru  SET barcode_id = 'djAx3tJM7pEN2lLhsrFOAzCEzMncfj4mngZmlB9n5EfMZxvGg7OlNhU6EJ7qbB6TiqY=' WHERE guru_id = 61;

-- [MATCH-exact] MUHAMMAD AZZAM AL BARIQ (1).png
-- Murid: MUHAMMAD AZZAM AL BARIQ (NIS: 2025070538) | QR: djAxjWkWgZOuogOnYAP49i8XvZnd2GyEthdKx1CfvEeef1AL+VvlbW3oI5wH/V/oo5E=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxjWkWgZOuogOnYAP49i8XvZnd2GyEthdKx1CfvEeef1AL+VvlbW3oI5wH/V/oo5E=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxjWkWgZOuogOnYAP49i8XvZnd2GyEthdKx1CfvEeef1AL+VvlbW3oI5wH/V/oo5E=';
UPDATE murid SET barcode_id = 'djAxjWkWgZOuogOnYAP49i8XvZnd2GyEthdKx1CfvEeef1AL+VvlbW3oI5wH/V/oo5E=' WHERE nis = '2025070538';

-- [TIDAK_DITEMUKAN] MUHAMMAD HAFIDH NASRULLAH.jpg
-- QR: djAxvnnVL7Z2JJko9PEs5s/9ozU6vXiZRHaSe08Fpp4EKVy1EkN7O2lzn0CsBAG+928=

-- [DUPLIKAT] MUHAMMAD IQBAL NUR.jpg
-- Kemungkinan: Murid:MUHAMMAD IQBAL MAULANA PUTRA | Murid:MUHAMMAD ZUHAIRIQBAL KHOIRUNNAS
-- QR: djAx0yYMsmOwpDjwu1/aUkSmSoi7uSepnQjqdv8BCXDr+PNt4so8GL2a8AUUZ/yOCpY=

-- [TIDAK_DITEMUKAN] MUHAMMAD KAFABIH.jpg
-- QR: djAxn3gythbj89mWQV/LMiJY1erP6kDArT507EW+scjmL/yUkIv0oezkw1RVQy0w/30=

-- [TIDAK_DITEMUKAN] MUHAMMAD NADHIF.jpg
-- QR: djAxhU/S1DlMKmf9N1z1whLlCjkJCkbHwmyq6/bMdy/kE67FqgjDcHVKI55L7UVfKi4=

-- [TIDAK_DITEMUKAN] MUHAMMAD RIZKI PUTRA WINARYA.jpg
-- QR: djAxOZa/vWWfIaxjkbLK3F9XS+f4vPu+8fwo9Xj0FOSgiQ3/cD3IM0BVScZr2ZcU4R0=

-- [TIDAK_DITEMUKAN] MUHAMMAD SYAFI ALAM EDY WIBOWO.jpg
-- QR: djAxDmaX5AHLS+QoLYIr7To61jbwqNYFNU0ouVoWvu0EuxuJ+4zgA0KL9ierpw5vQCg=

-- [TIDAK_DITEMUKAN] MUHAMMAD SYAFIIURRAHMAN.jpg
-- QR: djAxabqPeur7UME3oInk8x48ABSwNpf/+EkzUWFp6OVBMg6knmcVXEBMi+Q7m8nLsfY=

-- [TIDAK_DITEMUKAN] MUHAMMAD THOMY HILMY AZIZY.jpg
-- QR: djAx/xxWuZHlFImuznV4yt4xyxgPJAt5kXY7uRZJBpLkq8js/O8strcCeDFRjDbVVFk=

-- [TIDAK_DITEMUKAN] NAFISAH ALFADHILAH.jpg
-- QR: djAxolVpxs0WGBnM8asSJp32xckT8FM9yzBQfaltssWWbd83Gn9No9ddV2O2Kzgp/pU=

-- [MATCH-exact] NAFISAH AZ-ZAHRAH.jpg
-- Murid: NAFISAH AZ-ZAHRAH (NIS: 2025070461) | QR: djAxmpxIqYDQXPc5OmFqgL/9/elWphSPJmi7KWaFgTmmoN98mI+1RNtB8KpyaOWPKZg=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxmpxIqYDQXPc5OmFqgL/9/elWphSPJmi7KWaFgTmmoN98mI+1RNtB8KpyaOWPKZg=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxmpxIqYDQXPc5OmFqgL/9/elWphSPJmi7KWaFgTmmoN98mI+1RNtB8KpyaOWPKZg=';
UPDATE murid SET barcode_id = 'djAxmpxIqYDQXPc5OmFqgL/9/elWphSPJmi7KWaFgTmmoN98mI+1RNtB8KpyaOWPKZg=' WHERE nis = '2025070461';

-- [TIDAK_DITEMUKAN] NAJIHATU AZMI.jpg
-- QR: djAxBwLEt//Zolgm6HgicBVh8pyxAqXMa/Y87uGsxzY/hyH1BnFMlPo8wt12R7SKeuw=

-- [TIDAK_DITEMUKAN] NAJWA DURROTUS TSANIA.jpg
-- QR: djAxATVivYvx6vxeITtHdSf4zuoPgk0xY0EFiXtmOf5OuicpTeKMoGp1Jh5tnxbjT8k=

-- [TIDAK_DITEMUKAN] NAURA KAYLA AMALIA.jpg
-- QR: djAxhkR/ofAdGyO9KnUsvgdbmN9md+Tsd+CQ+/tbLKtaOXUB5r/LCsZZM4jyo1blx9I=

-- [TIDAK_DITEMUKAN] NEYLA MARITSA AZ ZAHRA.jpg
-- QR: djAx8xAiNVCL5Q1b4hdEm5vxPURmRrK3q4prT0W8zBAqcCQsvWQDVb3IwlSsfTb/a8Q=

-- [TIDAK_DITEMUKAN] NIKLA SOFIYATUL FAIZAH.jpg
-- QR: djAxqkbxdi5UoKrIudYDbUlRNAN1EvnXBfMDzgzldt9dZz8qJRii+MaI4Tjn9ZnXul4=

-- [TIDAK_DITEMUKAN] NIRMALA DIVA AURELLEA.jpg
-- QR: djAxqQvmfBCzoW7SBLqcM/OaIKui4UUOMql30773wMXRgmRHyvnWVNWgW0jh6SPAkyo=

-- [MATCH-exact] NUR FAZA KAMILA (1).png
-- Murid: NUR FAZA KAMILA (NIS: 2024070467) | QR: djAxr/osXMcppKlY9WH3r7kulBpQy7hUlCVdrXs8upRFyFJmfFFokHj/IOJHjIuPi8g=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxr/osXMcppKlY9WH3r7kulBpQy7hUlCVdrXs8upRFyFJmfFFokHj/IOJHjIuPi8g=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxr/osXMcppKlY9WH3r7kulBpQy7hUlCVdrXs8upRFyFJmfFFokHj/IOJHjIuPi8g=';
UPDATE murid SET barcode_id = 'djAxr/osXMcppKlY9WH3r7kulBpQy7hUlCVdrXs8upRFyFJmfFFokHj/IOJHjIuPi8g=' WHERE nis = '2024070467';

-- [TIDAK_DITEMUKAN] NURI MUSLICHATUL MA`RIFAH.jpg
-- QR: djAxdGyenU/5TXIUgjHSaiXdIisQ2I0i5v72v+pBTCviEg/gACQRlP+rRqWmzuAMXYU=

-- [TIDAK_DITEMUKAN] NURIYATURROHILLAH.jpg
-- QR: djAxazL/6m7auqh6ZNMw8bQ5AzjDtEtS7gwZKpZoqNFkD7OnD5r4zFq3O/pCaLdKh+E=

-- [TIDAK_DITEMUKAN] NURMA ZAZA KURININ.jpg
-- QR: djAxyzYqnRHLcu5v2986ErdUOlzlifD52XkFB6cjSQ9JQjLT478bpH6Hq3YzQOZyhBc=

-- [TIDAK_DITEMUKAN] NURUL CHOIRIYAH.jpg
-- QR: djAxHcE0ktthi16G8wam9yu4NTRcK+3y2HuvSRQLGnP1B4ietl1PCCtjUNBCr2Ghjjo=

-- [TIDAK_DITEMUKAN] NURUL HIDAYATUL AINIYA.jpg
-- QR: djAx1LF4750eX6mIWkzNf1JMRGtBg5GPFhfodslZAc0KCeNjLBYbbDSdoZV5dgfkgZI=

-- [MATCH-db-in-file] NUZILAT SHOFWATUL MAR`AH.jpg
-- Murid: NUZILAT SHOFWATUL MAR\'AH (NIS: 2025070093) | QR: djAx9I5Atclo12crMtXwa60I3m4uEmCkQDtm0LPnpeiQb6QClnJeqw4kFFlLOsgbz6o=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAx9I5Atclo12crMtXwa60I3m4uEmCkQDtm0LPnpeiQb6QClnJeqw4kFFlLOsgbz6o=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAx9I5Atclo12crMtXwa60I3m4uEmCkQDtm0LPnpeiQb6QClnJeqw4kFFlLOsgbz6o=';
UPDATE murid SET barcode_id = 'djAx9I5Atclo12crMtXwa60I3m4uEmCkQDtm0LPnpeiQb6QClnJeqw4kFFlLOsgbz6o=' WHERE nis = '2025070093';

-- [TIDAK_DITEMUKAN] PRANANDARU SURYO SASONGKO.jpg
-- QR: djAxv27GBDzUCxnDjZ/m1BP+R4VwI0sg6RO1elwmTIMjQacwEYfu5WbqziK64oLDLo8=

-- [TIDAK_DITEMUKAN] QORIDINY FAJRIN NIHAYATUS SHOLIHAH.jpg
-- QR: djAx4Kt+sHm0SUgQsyzGgSmc/NP/gWjnnGE5CHcm4iWH67o23MW9AbVzbvyZltN/dkM=

-- [MATCH-exact] RAIHAN AUFAR ALDIVA ARSYIL (1).jpg
-- Murid: RAIHAN AUFAR ALDIVA ARSYIL (NIS: 2025070537) | QR: djAxUTnbfebXOANfFq6FdiZNV92d6mGCiwQj8ukW5N9ntwueuWVatQykVACmcXTfqgI=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxUTnbfebXOANfFq6FdiZNV92d6mGCiwQj8ukW5N9ntwueuWVatQykVACmcXTfqgI=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxUTnbfebXOANfFq6FdiZNV92d6mGCiwQj8ukW5N9ntwueuWVatQykVACmcXTfqgI=';
UPDATE murid SET barcode_id = 'djAxUTnbfebXOANfFq6FdiZNV92d6mGCiwQj8ukW5N9ntwueuWVatQykVACmcXTfqgI=' WHERE nis = '2025070537';

-- [TIDAK_DITEMUKAN] RANI HARITOTUL MAHMUDAH.jpg
-- QR: djAxMaghTh76SWVLYjicGtdwlc1RBabujiZfgt1nHPGGzZGlYReo/TucIP61iJ0x7O0=

-- [TIDAK_DITEMUKAN] RICHA UJIMATUS RISNAWATI.jpg
-- QR: djAxeNSgz2HwZrR8f9SERJuPb+JfWOfzF63G/stgfp7b8L+kHvBVkv0G/R7mzrQn/FI=

-- [TIDAK_DITEMUKAN] RIFDATUL AISYIN FARIQA.jpg
-- QR: djAxUyPgogJjB4chb8GsIzfOS8Fo7CO6fvVEtRZpeThsgzkbymdDFcwlPcB1usemJzs=

-- [MATCH-db-in-file] RIFVANDO M. AKBAR MAULANA.jpg
-- Murid: AKBAR MAULANA (NIS: 2025070272) | QR: djAxRMkxtsxVYGb3/MbMa4CMqnClb/5wnUoAlgzE24P0gOnsKSPSnbtGu2ulShJAWps=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxRMkxtsxVYGb3/MbMa4CMqnClb/5wnUoAlgzE24P0gOnsKSPSnbtGu2ulShJAWps=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxRMkxtsxVYGb3/MbMa4CMqnClb/5wnUoAlgzE24P0gOnsKSPSnbtGu2ulShJAWps=';
UPDATE murid SET barcode_id = 'djAxRMkxtsxVYGb3/MbMa4CMqnClb/5wnUoAlgzE24P0gOnsKSPSnbtGu2ulShJAWps=' WHERE nis = '2025070272';

-- [MATCH-exact] ROBI`AH AL-ADHAWIYAH.jpg
-- Murid: ROBI`AH AL-ADHAWIYAH (NIS: 2024070022) | QR: djAx4VcROayuD+2N29ubmE9hL3VB68HgLig6q+hXmP4AcVmihivOiVj3me6/5Hsb7fM=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAx4VcROayuD+2N29ubmE9hL3VB68HgLig6q+hXmP4AcVmihivOiVj3me6/5Hsb7fM=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAx4VcROayuD+2N29ubmE9hL3VB68HgLig6q+hXmP4AcVmihivOiVj3me6/5Hsb7fM=';
UPDATE murid SET barcode_id = 'djAx4VcROayuD+2N29ubmE9hL3VB68HgLig6q+hXmP4AcVmihivOiVj3me6/5Hsb7fM=' WHERE nis = '2024070022';

-- [MATCH-exact] ROSSALIA BELLA RAISYA (1).jpg
-- Murid: ROSSALIA BELLA RAISYA (NIS: 2024070443) | QR: djAxtmijeDCPoJ3bAHMAclGwyzf6PYLdUCFQGmUMMIIUuPDyUpGqUN8u4Knrje6r7ts=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxtmijeDCPoJ3bAHMAclGwyzf6PYLdUCFQGmUMMIIUuPDyUpGqUN8u4Knrje6r7ts=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxtmijeDCPoJ3bAHMAclGwyzf6PYLdUCFQGmUMMIIUuPDyUpGqUN8u4Knrje6r7ts=';
UPDATE murid SET barcode_id = 'djAxtmijeDCPoJ3bAHMAclGwyzf6PYLdUCFQGmUMMIIUuPDyUpGqUN8u4Knrje6r7ts=' WHERE nis = '2024070443';

-- [TIDAK_DITEMUKAN] ROSYIDAH ZUHROTUN NISA.jpg
-- QR: djAxZ+14vpci70YSlnv8NwOMkKhSo/0cWWrSWjOYcrTtQ5MpxOHm98OM1sLbQdseNmA=

-- [TIDAK_DITEMUKAN] SALAHUDDIN ABDUL AZIZ.jpg
-- QR: djAxAFchUs3iYqwzi9by0F0MnAo3Ld3vbmm/zQkTH9u0lwwB4rM9Ke/5M9diCpaX7pQ=

-- [TIDAK_DITEMUKAN] SA`DI NUR MUHAMMAD.jpg
-- QR: djAxopP03P8umbhzxbaW3LAvrBt1chUjurd3jGhbtpr1z5PTY3QgWoJ9sEsgYuh1J0Y=

-- [TIDAK_DITEMUKAN] SHABRINA RAHMADANI.jpg
-- QR: djAxoXnqpzSjtnYO2nNv/KMumIsJMNMeBmOSbd1QREduIY3rDJeUEO2hQm09g8jfPvI=

-- [TIDAK_DITEMUKAN] SHAFIRA NUR ANGGRAENI OKTAVIA.jpg
-- QR: djAx7oS56NdvuIrUCmM4i7osGuIU9BJmowDMsNa3Yyf06N/Qir2nStS8SIQuORypuXM=

-- [TIDAK_DITEMUKAN] SITI DJAMILAH, DRA.jpg
-- QR: djAxZ1Uu6c8jPpnEf5AZxqK6OQI91YmYZCnchkp2SMOPknJncc2T4a19v5ks8Msn6cE=

-- [MATCH-db-in-file] SITI LATHIFATUS SUNIYAH, DRA. M.AG. M.P.jpg
-- Guru: Hj. Siti Lathifatus Sun\'iyah (ID: 59) | QR: djAxM4p4gm7GEv+wbbvKtVFHGMQb2i+r3y7YubRfn4jilP3A78bIOoTDV+hWmVCHJu0=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxM4p4gm7GEv+wbbvKtVFHGMQb2i+r3y7YubRfn4jilP3A78bIOoTDV+hWmVCHJu0=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxM4p4gm7GEv+wbbvKtVFHGMQb2i+r3y7YubRfn4jilP3A78bIOoTDV+hWmVCHJu0=';
UPDATE guru  SET barcode_id = 'djAxM4p4gm7GEv+wbbvKtVFHGMQb2i+r3y7YubRfn4jilP3A78bIOoTDV+hWmVCHJu0=' WHERE guru_id = 59;

-- [TIDAK_DITEMUKAN] SYAADAH.jpg
-- QR: djAx/w35qpPiFRTPV46LTmmnuVgEc7BWMOsKLsnmssBS2B410jNIuUviT/+1NK+4Ry4=

-- [TIDAK_DITEMUKAN] SYAFAAT AL AMIN.jpg
-- QR: djAxJy8vXU86foHp403yJKitYwnM3E61mx56ozgu2hv06f3E8avWin/3UcKiFRgG0bI=

-- [MATCH-exact] SYAFIQOH AS-SHOFI.jpg
-- Murid: SYAFIQOH AS-SHOFI (NIS: 2025070340) | QR: djAxln98zdDj5fEPkggaJChCZUKZgsmDbLLvZ3FAAwsM8zdoIgW+I1RHLwOb3UlustM=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxln98zdDj5fEPkggaJChCZUKZgsmDbLLvZ3FAAwsM8zdoIgW+I1RHLwOb3UlustM=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxln98zdDj5fEPkggaJChCZUKZgsmDbLLvZ3FAAwsM8zdoIgW+I1RHLwOb3UlustM=';
UPDATE murid SET barcode_id = 'djAxln98zdDj5fEPkggaJChCZUKZgsmDbLLvZ3FAAwsM8zdoIgW+I1RHLwOb3UlustM=' WHERE nis = '2025070340';

-- [TIDAK_DITEMUKAN] SYAKIRAH SALMA RAIHANAH.jpg
-- QR: djAxxOZpIbKYjIL6R0jAY8zDD2tQiuxaFVC2MhNYse9ho7V/2/ECdNi+zT+iN0x1FCM=

-- [MATCH-exact] SYIFAUL MAULIDATUN NISA`.jpg
-- Guru: Ustd. Syifaul Maulidatun Nisa\' (ID: 114) | QR: djAxkm+K7O8qUdFswS/oC5M9kF3EhLI8pHHeoi5Un+rK71uP9jUaMGmCnds5Q/AhTiE=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxkm+K7O8qUdFswS/oC5M9kF3EhLI8pHHeoi5Un+rK71uP9jUaMGmCnds5Q/AhTiE=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxkm+K7O8qUdFswS/oC5M9kF3EhLI8pHHeoi5Un+rK71uP9jUaMGmCnds5Q/AhTiE=';
UPDATE guru  SET barcode_id = 'djAxkm+K7O8qUdFswS/oC5M9kF3EhLI8pHHeoi5Un+rK71uP9jUaMGmCnds5Q/AhTiE=' WHERE guru_id = 114;

-- [TIDAK_DITEMUKAN] TISYA ALYRA PUTRI ADEVIO.jpg
-- QR: djAxADXBQIaw6PrjuAJUj3C5FrG9ZeOIFu7n2eGQD312jcc1Hyr0w9iXHkUbO5Agxp0=

-- [MATCH-exact] TITIN NUR MAULIDIA (1).png
-- Murid: TITIN NUR MAULIDIA (NIS: 2025070621) | QR: djAxLf5+PhqU8JZBzLj2AgHzO0548+TgeTax4C3nG01akQBMmGDuJIEcgcJXNcnR11E=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxLf5+PhqU8JZBzLj2AgHzO0548+TgeTax4C3nG01akQBMmGDuJIEcgcJXNcnR11E=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxLf5+PhqU8JZBzLj2AgHzO0548+TgeTax4C3nG01akQBMmGDuJIEcgcJXNcnR11E=';
UPDATE murid SET barcode_id = 'djAxLf5+PhqU8JZBzLj2AgHzO0548+TgeTax4C3nG01akQBMmGDuJIEcgcJXNcnR11E=' WHERE nis = '2025070621';

-- [MATCH-exact] TRIANOVA AMALIA AZ-ZAHRA.jpg
-- Murid: TRIANOVA AMALIA AZ-ZAHRA (NIS: 2025070578) | QR: djAxIhZ8a0NopWuGUWkgPQoflpnnaGbCBPojYdRzAS/3lJrjncwyY8HIDTo4gqtNw28=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxIhZ8a0NopWuGUWkgPQoflpnnaGbCBPojYdRzAS/3lJrjncwyY8HIDTo4gqtNw28=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxIhZ8a0NopWuGUWkgPQoflpnnaGbCBPojYdRzAS/3lJrjncwyY8HIDTo4gqtNw28=';
UPDATE murid SET barcode_id = 'djAxIhZ8a0NopWuGUWkgPQoflpnnaGbCBPojYdRzAS/3lJrjncwyY8HIDTo4gqtNw28=' WHERE nis = '2025070578';

-- [TIDAK_DITEMUKAN] ULIL MUKARROMAH.jpg
-- QR: djAxH/k0BHwYV/wb3qapZWiY3QEO3sg8t3nM2NdFKuJHi3zYjr1PRledmZvQfD2PkPE=

-- [TIDAK_DITEMUKAN] ZAHROTIN NAFIAH.jpg
-- QR: djAxDeQkpNoXmj7ny58ByH3WJq/qgM0B0JuvpD0rxZaAF3o0LCvrMxhdkC5LV2zbtNY=

-- [TIDAK_DITEMUKAN] ZAININA ZUBI ZARRETA.jpg
-- QR: djAxv4r+pRMu4XlmYl0bMw+GREuvfzW9a9BeD8zHiRJ/VrnaOEyALoM6ynwt8Vf5/9A=

-- [TIDAK_DITEMUKAN] ZAKIYATUL MAULIDIYAH.jpg
-- QR: djAxcT5xuseY5bFt6lSW65prMt/jCnNCiyTBYPJJVS4zCIzMMR1vlD9QFgQU1R3gDVY=

-- [TIDAK_DITEMUKAN] ZHAAFIRAH NUR FADHILA.jpg
-- QR: djAxeZ55h8+VWuJfAvPYNlEipYn5OAgYi/nD7eE4YdiHJKLnLkPtVC0SBYWvsB2CDS0=

-- [TIDAK_DITEMUKAN] ZHARIIFAH NUR FADHILA.jpg
-- QR: djAxXjGhIj0Co7pEiplThIpekL7LXMv/WLD9TiASrZ+gIVvarjWiDKb56cpNPKQ1FbU=

-- [MATCH-file-in-db] ZUHRO NURMALA M. R.jpg
-- Guru: Ustd. Zuhro Nurmala (ID: 124) | QR: djAxmDZkszvcIWPLvrRgooxpmYfF0K0wncj21m0opaLV8/Q/riUur2ir9RqWOV+mpF8=
UPDATE murid SET barcode_id = NULL WHERE barcode_id = 'djAxmDZkszvcIWPLvrRgooxpmYfF0K0wncj21m0opaLV8/Q/riUur2ir9RqWOV+mpF8=';
UPDATE guru  SET barcode_id = NULL WHERE barcode_id = 'djAxmDZkszvcIWPLvrRgooxpmYfF0K0wncj21m0opaLV8/Q/riUur2ir9RqWOV+mpF8=';
UPDATE guru  SET barcode_id = 'djAxmDZkszvcIWPLvrRgooxpmYfF0K0wncj21m0opaLV8/Q/riUur2ir9RqWOV+mpF8=' WHERE guru_id = 124;

-- [TIDAK_DITEMUKAN] ZULIANA HIDAYATUSZZAHRAH.jpg
-- QR: djAx6dAO+dihoDLeF6M4bAp8Ksgw3YYaayPmLtqBdlcmazjHkWJLZhjZ3cJlKO80v4Q=
