import { NextResponse } from 'next/server';
import pool from '@/lib/db';

/**
 * GET /api/migrate-santri-baru-2025
 * Self-contained in-memory API route to execute 268 Santri Baru migration queries on cPanel.
 * No external file dependencies. Safe & Idempotent.
 */

const SQL_STATEMENTS: string[] = [
  "UPDATE murid SET kelas_madin_id = 24, updated_at = NOW() WHERE nis = '2026050035'; -- ALIA NAFIZAH NUR ALIFAH -> 1 Ula A Putri",
  "UPDATE murid SET kelas_madin_id = 24, updated_at = NOW() WHERE nis = '2026050028'; -- AMIROTUL UMMAH -> 1 Ula A Putri",
  "UPDATE murid SET kelas_madin_id = 24, updated_at = NOW() WHERE nis = '2026050037'; -- BILQIS SYAFA`ATUL ULA -> 1 Ula A Putri",
  "UPDATE murid SET kelas_madin_id = 24, updated_at = NOW() WHERE nis = '2026050017'; -- KHALISA NUR FADILAH -> 1 Ula A Putri",
  "UPDATE murid SET kelas_madin_id = 24, updated_at = NOW() WHERE nis = '2026050023'; -- NABILLA FATHIN TIFANNY -> 1 Ula A Putri",
  "UPDATE murid SET kelas_madin_id = 24, updated_at = NOW() WHERE nis = '2024070608'; -- NAYLA SALSABILA -> 1 Ula A Putri",
  "UPDATE murid SET kelas_madin_id = 24, updated_at = NOW() WHERE nis = '2026050074'; -- NAURA ZIVANA AGUSTIN -> 1 Ula A Putri",
  "UPDATE murid SET kelas_madin_id = 24, updated_at = NOW() WHERE nis = '2023080259'; -- ZAHWA NUR AINI -> 1 Ula A Putri",
  "UPDATE murid SET kelas_madin_id = 24, updated_at = NOW() WHERE nis = '2026050102'; -- ZAHIRA NASYA AL MAIRA -> 1 Ula A Putri",
  "UPDATE murid SET kelas_madin_id = 25, updated_at = NOW() WHERE nis = '2026050075'; -- AF`IDATUL MUKHOLLISHOH -> 1 Ula B Putri",
  "UPDATE murid SET kelas_madin_id = 25, updated_at = NOW() WHERE nis = '2026050029'; -- ANIQOTUN NAFISAH -> 1 Ula B Putri",
  "UPDATE murid SET kelas_madin_id = 25, updated_at = NOW() WHERE nis = '2026050084'; -- ANNISA JAZILATUR RAHMA -> 1 Ula B Putri",
  "UPDATE murid SET kelas_madin_id = 25, updated_at = NOW() WHERE nis = '2026050092'; -- ARZATI KARIMATUL FIRDAUZY -> 1 Ula B Putri",
  "UPDATE murid SET kelas_madin_id = 25, updated_at = NOW() WHERE nis = '2026050070'; -- DAHAYU LARASATI BUDIONO -> 1 Ula B Putri",
  "UPDATE murid SET kelas_madin_id = 25, updated_at = NOW() WHERE nis = '2026050056'; -- DINDA ALIYA KANZA AZ ZAHRA -> 1 Ula B Putri",
  "UPDATE murid SET kelas_madin_id = 25, updated_at = NOW() WHERE nis = '2026050094'; -- ISTIQLALLU RO`ADDINI -> 1 Ula B Putri",
  "UPDATE murid SET kelas_madin_id = 25, updated_at = NOW() WHERE nis = '2026050091'; -- KINARYA ILMALADZAH KAMIL -> 1 Ula B Putri",
  "UPDATE murid SET kelas_madin_id = 25, updated_at = NOW() WHERE nis = '2026050025'; -- NAJWA SYATHIUL INAYAH -> 1 Ula B Putri",
  "UPDATE murid SET kelas_madin_id = 25, updated_at = NOW() WHERE nis = '2026050076'; -- RAISAH TADZKIROTUN NAFISAH -> 1 Ula B Putri",
  "UPDATE murid SET kelas_madin_id = 26, updated_at = NOW() WHERE nis = '2026050058'; -- ADIBA SHAKILA ATMARINI -> 1 Ula C Putri",
  "UPDATE murid SET kelas_madin_id = 26, updated_at = NOW() WHERE nis = '2026050036'; -- AISYA SALSA NABILA -> 1 Ula C Putri",
  "UPDATE murid SET kelas_madin_id = 26, updated_at = NOW() WHERE nis = '2026050069'; -- ASHIVA MAHARANI SAFITRI -> 1 Ula C Putri",
  "UPDATE murid SET kelas_madin_id = 26, updated_at = NOW() WHERE nis = '2026050016'; -- AULIA NUR AYSIFA -> 1 Ula C Putri",
  "UPDATE murid SET kelas_madin_id = 26, updated_at = NOW() WHERE nis = '2026050073'; -- ISMI HABIBATUN NIRMALA -> 1 Ula C Putri",
  "UPDATE murid SET kelas_madin_id = 26, updated_at = NOW() WHERE nis = '2026050046'; -- KAISYA AZKAYRA ELFARIZAH -> 1 Ula C Putri",
  "UPDATE murid SET kelas_madin_id = 26, updated_at = NOW() WHERE nis = '2026050087'; -- KHILYATUL AINIYAH -> 1 Ula C Putri",
  "UPDATE murid SET kelas_madin_id = 26, updated_at = NOW() WHERE nis = '2026050079'; -- NADIYAH MAULIDAH HUSNA -> 1 Ula C Putri",
  "UPDATE murid SET kelas_madin_id = 26, updated_at = NOW() WHERE nis = '2026050080'; -- SAFFANAH NAZHIHAH ANDINIYANTI -> 1 Ula C Putri",
  "UPDATE murid SET kelas_madin_id = 26, updated_at = NOW() WHERE nis = '2026050057'; -- SAHLA ILMA NAFIA -> 1 Ula C Putri",
  "UPDATE murid SET kelas_madin_id = 26, updated_at = NOW() WHERE nis = '2026050099'; -- SANIYAH BILQIS HUMAROH -> 1 Ula C Putri",
  "UPDATE murid SET kelas_madin_id = 26, updated_at = NOW() WHERE nis = '2026050078'; -- STELLA PUSPITA ARVI TEFANNY -> 1 Ula C Putri",
  "UPDATE murid SET kelas_madin_id = 26, updated_at = NOW() WHERE nis = '2026050019'; -- ZAHIRA AKTAVIA -> 1 Ula C Putri",
  "UPDATE murid SET kelas_madin_id = 14, updated_at = NOW() WHERE nis = '2023080686'; -- ADHILLA MAGHFIROTUL FAJARINA -> 1 Wustho A Putri",
  "UPDATE murid SET kelas_madin_id = 14, updated_at = NOW() WHERE nis = '2023080654'; -- AF`IDATUL HARIROH AL AFIFI -> 1 Wustho A Putri",
  "UPDATE murid SET kelas_madin_id = 14, updated_at = NOW() WHERE nis = '2023080665'; -- ALMIRA WIRA ANINDY -> 1 Wustho A Putri",
  "UPDATE murid SET kelas_madin_id = 14, updated_at = NOW() WHERE nis = '2023080513'; -- AMIRAH KHAIROH SALSABILA -> 1 Wustho A Putri",
  "UPDATE murid SET kelas_madin_id = 14, updated_at = NOW() WHERE nis = '2023080612'; -- ANIFA HANIYYA SHOLIHAH -> 1 Wustho A Putri",
  "UPDATE murid SET kelas_madin_id = 14, updated_at = NOW() WHERE nis = '2023080636'; -- ANNISA FITRI KARISMAWATI -> 1 Wustho A Putri",
  "UPDATE murid SET kelas_madin_id = 14, updated_at = NOW() WHERE nis = '2025080670'; -- AZZA AZKIYA AL FIRDAUS -> 1 Wustho A Putri",
  "UPDATE murid SET kelas_madin_id = 14, updated_at = NOW() WHERE nis = '2023080611'; -- BIRNIS BUTSAINAH BATLA -> 1 Wustho A Putri",
  "UPDATE murid SET kelas_madin_id = 14, updated_at = NOW() WHERE nis = '2023080633'; -- INAYA WULANDARI -> 1 Wustho A Putri",
  "UPDATE murid SET kelas_madin_id = 14, updated_at = NOW() WHERE nis = '2023080641'; -- KHUMAIROTUN NAFEEZA NURDIANA -> 1 Wustho A Putri",
  "UPDATE murid SET kelas_madin_id = 14, updated_at = NOW() WHERE nis = '2023080673'; -- LUJENG DEA SHOFIAH -> 1 Wustho A Putri",
  "UPDATE murid SET kelas_madin_id = 14, updated_at = NOW() WHERE nis = '2023080610'; -- MEYDHINA SYAFIRA -> 1 Wustho A Putri",
  "UPDATE murid SET kelas_madin_id = 14, updated_at = NOW() WHERE nis = '2023080618'; -- MILA FATMAWATI -> 1 Wustho A Putri",
  "UPDATE murid SET kelas_madin_id = 14, updated_at = NOW() WHERE nis = '2026050013'; -- NAZNIN QONITATI APRILIYA -> 1 Wustho A Putri",
  "UPDATE murid SET kelas_madin_id = 14, updated_at = NOW() WHERE nis = '2026050041'; -- NIZLA ZILFI FARHIYAH -> 1 Wustho A Putri",
  "UPDATE murid SET kelas_madin_id = 14, updated_at = NOW() WHERE nis = '2023080619'; -- NUR ABIBAH -> 1 Wustho A Putri",
  "UPDATE murid SET kelas_madin_id = 14, updated_at = NOW() WHERE nis = '2024070359'; -- PUTRI AYU RAMADHANI -> 1 Wustho A Putri",
  "UPDATE murid SET kelas_madin_id = 14, updated_at = NOW() WHERE nis = '2026050086'; -- YUANANDA KARUNIA APRILLIA -> 1 Wustho A Putri",
  "UPDATE murid SET kelas_madin_id = 14, updated_at = NOW() WHERE nis = '2026050012'; -- ZAHIRA MAHESA PUTRI -> 1 Wustho A Putri",
  "UPDATE murid SET kelas_madin_id = 15, updated_at = NOW() WHERE nis = '2026050063'; -- ANASTASYA KIRANA AFANDY -> 1 Wustho B Putri",
  "UPDATE murid SET kelas_madin_id = 15, updated_at = NOW() WHERE nis = '2023080696'; -- ARIELLA AURORA MAHESWARI -> 1 Wustho B Putri",
  "UPDATE murid SET kelas_madin_id = 15, updated_at = NOW() WHERE nis = '2026050039'; -- AYU LATIFATURROBI `UTSANNY -> 1 Wustho B Putri",
  "UPDATE murid SET kelas_madin_id = 15, updated_at = NOW() WHERE nis = '2026050098'; -- AZQIYATUL IMAMIYAH -> 1 Wustho B Putri",
  "UPDATE murid SET kelas_madin_id = 15, updated_at = NOW() WHERE nis = '2026050014'; -- CHAURA AZKA NAFILAH -> 1 Wustho B Putri",
  "UPDATE murid SET kelas_madin_id = 15, updated_at = NOW() WHERE nis = '2023080640'; -- HANIFAH QORY NA`AFIASYAH -> 1 Wustho B Putri",
  "UPDATE murid SET kelas_madin_id = 15, updated_at = NOW() WHERE nis = '2023080440'; -- MAULIDAH BINTA BAIZA -> 1 Wustho B Putri",
  "UPDATE murid SET kelas_madin_id = 15, updated_at = NOW() WHERE nis = '2026050034'; -- NAYSILA AL TANISA MAGHFIRO -> 1 Wustho B Putri",
  "UPDATE murid SET kelas_madin_id = 15, updated_at = NOW() WHERE nis = '2026050077'; -- NUR NAILUL MUNNAH -> 1 Wustho B Putri",
  "UPDATE murid SET kelas_madin_id = 15, updated_at = NOW() WHERE nis = '2026050095'; -- YASMIN IRDINA CAMELIA -> 1 Wustho B Putri",
  "UPDATE murid SET kelas_madin_id = 15, updated_at = NOW() WHERE nis = '2026050054'; -- ZUHROTUN NUR AFIFAH -> 1 Wustho B Putri",
  "UPDATE murid SET kelas_madin_id = 16, updated_at = NOW() WHERE nis = '2023080647'; -- ANINDHITA ZAHROTUN NAFIZAH -> 1 Wustho C Putri",
  "UPDATE murid SET kelas_madin_id = 16, updated_at = NOW() WHERE nis = '2023080645'; -- DINDA CITRA ADILIYA -> 1 Wustho C Putri",
  "UPDATE murid SET kelas_madin_id = 16, updated_at = NOW() WHERE nis = '2023080616'; -- EVIE RAHMAWATI -> 1 Wustho C Putri",
  "UPDATE murid SET kelas_madin_id = 16, updated_at = NOW() WHERE nis = '2026050010'; -- LOVELY ALFARINI ERIDANI -> 1 Wustho C Putri",
  "UPDATE murid SET kelas_madin_id = 16, updated_at = NOW() WHERE nis = '2026050011'; -- LUTFIAH ZAHRA TALITA -> 1 Wustho C Putri",
  "UPDATE murid SET kelas_madin_id = 16, updated_at = NOW() WHERE nis = '2023080638'; -- MEISYA ANGGUN CAHYA ADI -> 1 Wustho C Putri",
  "UPDATE murid SET kelas_madin_id = 16, updated_at = NOW() WHERE nis = '2026050009'; -- NUR AIDA RAFIAH -> 1 Wustho C Putri",
  "UPDATE murid SET kelas_madin_id = 16, updated_at = NOW() WHERE nis = '2026050045'; -- QONITAH QATTRUNNADA ALWAFA -> 1 Wustho C Putri",
  "UPDATE murid SET kelas_madin_id = 16, updated_at = NOW() WHERE nis = '2023080702'; -- TIARA NUR FAIZAH -> 1 Wustho C Putri",
  "UPDATE murid SET kelas_madin_id = 16, updated_at = NOW() WHERE nis = '2023080656'; -- UMMI AMIRATUS SHOLIHAH -> 1 Wustho C Putri",
  "UPDATE murid SET kelas_madin_id = 16, updated_at = NOW() WHERE nis = '2023080659'; -- NIKEN AJENG LESTARI -> 1 Wustho C Putri",
  "UPDATE murid SET kelas_madin_id = 16, updated_at = NOW() WHERE nis = '2023080675'; -- NOLALINKA INDY PUTRI -> 1 Wustho C Putri",
  "UPDATE murid SET kelas_madin_id = 16, updated_at = NOW() WHERE nis = '2023080699'; -- NUR SIELVA NABYLA PUTRI -> 1 Wustho C Putri",
  "UPDATE murid SET kelas_madin_id = 16, updated_at = NOW() WHERE nis = '2023080658'; -- SU`DAA ARINAL UDLHIYYAH -> 1 Wustho C Putri",
  "UPDATE murid SET kelas_madin_id = 16, updated_at = NOW() WHERE nis = '2023080469'; -- WAHIDA RASYADA ARINI -> 1 Wustho C Putri",
  "UPDATE murid SET kelas_madin_id = 16, updated_at = NOW() WHERE nis = '2023080656'; -- UMMI AMIRATUS SHOLIHAH -> 1 Wustho C Putri",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'AISYI KASYFA JAMALA', '2025077001', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077001');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'AKIFA NAILA', '2025077002', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077002');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ALZARIN NAYLA AZZAHRA', '2025077003', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077003');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ANDINI FAIQOTUL HIMMAH', '2025077004', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077004');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'AURELLIA NENCY ALDIVA', '2025077005', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077005');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'AZKA AYU WIDJAYA', '2025077006', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077006');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'BIAUNI SATAKUNU NAJMA', '2025077007', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077007');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'CALISTA INDRIA PUTRI MUSTOFA', '2025077008', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077008');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'DHURRIYA NAILA TALITA', '2025077009', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077009');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'DIAN INDAH PERMATA SARI', '2025077010', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077010');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'FARAH ADELIA AZIZ', '2025077011', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077011');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'FARAH LUTFIA ALFITRI', '2025077012', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077012');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'FATHIN SIDQIYAH ZEN IMAMI', '2025077013', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077013');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'FRISYA ZAHWA ANINDYAH', '2025077014', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077014');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'INTAN ZAHRAH MUFIDAH', '2025077015', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077015');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'LAILATUL FADLIYAH', '2025077016', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077016');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'MEI LINDA ZAHROTUL MAWADDAH', '2025077017', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077017');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'MELY ATIKA LAYLA', '2025077018', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077018');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NABILA KHANSA AZZAHWA', '2025077019', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077019');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NIRVANA SYIFA''UL AULIYAH', '2025077020', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077020');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NOFILIA DWI RIZKIA', '2025077021', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077021');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'OKTAVIA ZULIANTI', '2025077022', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077022');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'RAIHANA TALITA FAHRIANI', '2025077023', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077023');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'RIFDA AMINATUS SA''ADAH', '2025077024', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077024');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'RITA RAHMAH WATI', '2025077025', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077025');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'RIZKA HELMI FITRIYANTI', '2025077026', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077026');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'SASKIANA TANTRI', '2025077027', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077027');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'SITI NUR MALLA HAYATI ALIFAH R', '2025077028', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077028');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'TASYA NABILA AYU ZAHILA CITRA W', '2025077029', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077029');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'TIYA AYU LESTARI', '2025077030', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077030');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'VANIYA ALMA SALSABILA', '2025077031', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077031');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ZAHRA ZAKIYATUL MISKIYAH', '2025077032', 'Perempuan', 24, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077032');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ADIBA AZZAHRA NURUS SA''BANA', '2025077033', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077033');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ADIBA IZDIHAR AURORA MAHESWARI', '2025077034', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077034');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ALICIA CELIN MILANDRA', '2025077035', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077035');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ALILA HALWA ADIBAH', '2025077036', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077036');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ALIZA NAFISAN', '2025077037', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077037');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'AQILA AZZAHRA', '2025077038', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077038');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ARINTA MAGHFIROH', '2025077039', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077039');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'AULIA IZZATUN NISA', '2025077040', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077040');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'AVRILA NATANIA EVELIN', '2025077041', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077041');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'DESY NAURA CAHYA NINGSIH', '2025077042', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077042');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'FAJRA NADA NADIFA', '2025077043', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077043');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'FARISYAH ABIDANNADHIFAH', '2025077044', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077044');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'FATIA HANIN ARIFAH', '2025077045', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077045');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'GIGIS ALBIN NABIHA SETIYA INDRAYATI', '2025077046', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077046');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'HAFIZA ASKA AQILA', '2025077047', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077047');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'HILYATUN NAJIHAH', '2025077048', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077048');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'MARSYA DWI PERTIWI', '2025077049', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077049');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'MAWLYA ANALISTYA MALICHAH', '2025077050', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077050');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NADZWA AULIA PUTRI', '2025077051', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077051');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NAFISAH ANINDYA', '2025077052', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077052');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NAJWA KHAIRA WILDA', '2025077053', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077053');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NAJWA KHOIRO WILDA', '2025077054', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077054');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NURUL UBAIDAH ZULFATUL UMAIROH', '2025077055', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077055');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'PRITA EKA SEPTIANI', '2025077056', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077056');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'QAIREEN ALMAIRA ASRORI', '2025077057', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077057');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'REVI DWI ANGGRAENI', '2025077058', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077058');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'RIFQIYYAH ISNANI AMALIAH', '2025077059', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077059');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'RIYANA DWI KHOIROTUNNISA''', '2025077060', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077060');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'SEKAR KENCANA UNGU', '2025077061', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077061');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'SYABRINA FAQIYYAH NAZIFA', '2025077062', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077062');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'SYIFA PUTRI FAUZIAH', '2025077063', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077063');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'TALITHA RAYHANAH', '2025077064', 'Perempuan', 25, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077064');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ADIBA SHAKILA RABBANI', '2025077065', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077065');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'AJENG AYU ANJANI', '2025077066', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077066');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ALMIRA IRDINA PUTRI', '2025077067', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077067');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ALTHA FUNNISA SALSABILA AZRINA', '2025077068', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077068');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ALYSA SHAFA AZZURA', '2025077069', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077069');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ANANDA WIDYA ROHMAH APRILIA', '2025077070', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077070');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ANGGUN AQILAH SHIDQIYAH', '2025077071', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077071');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ANGGUN KEISA ELHANAH', '2025077072', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077072');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'AZKIYA QANITA PUTRI', '2025077073', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077073');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'AZ-ZAHRA NOVITA RAHAYU', '2025077074', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077074');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'AZZALIA INTAN DAFIANATASYAH', '2025077075', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077075');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'CHOLILATUL ALIVINA', '2025077076', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077076');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ELISA NABILLA PUTRI', '2025077077', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077077');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ELNAURA PRAMESTI', '2025077078', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077078');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'FIRLY NIHAYATUL QUDSIYA', '2025077079', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077079');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'HAMIDAH FI''ISYATIN RODLIYAH', '2025077080', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077080');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'I''ANATUL MAULA ANJANI AL-AJMA''IN', '2025077081', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077081');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'KHOIRUN NISA RAMADHANI', '2025077082', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077082');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'LUM''ATUN NUZULIN NADA', '2025077083', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077083');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'MUTHI ATIN ADIBAH', '2025077084', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077084');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NABIHAH AGHNIYAH ROHMAH', '2025077085', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077085');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NATASYA PUTRI', '2025077086', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077086');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NAURAH ARIJ JUNAITA', '2025077087', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077087');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NAYLA MAGHFIRO', '2025077088', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077088');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'PUTRI KHUMAIRAH AL-JANNAH', '2025077089', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077089');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'RACHEL KIRANA SHAHESYA', '2025077090', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077090');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'RAHMA CATUR ASYIFA', '2025077091', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077091');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'SAHALISA KIRANA PUTRI', '2025077092', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077092');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'SIFANA RHAMADANI', '2025077093', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077093');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'TSANIA NURUL ILMA', '2025077094', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077094');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'UMMI DZAKIROH AFTANIA', '2025077095', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077095');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'VIRLY REVALINA', '2025077096', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077096');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ZABIR FAZA HAMIDAH', '2025077097', 'Perempuan', 26, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077097');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'AHDA ROSE FLORA', '2025077098', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077098');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'AJMALA PUTRI MAULIDIYAH', '2025077099', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077099');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'AKSANNIA FITROTUN NAJIA', '2025077100', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077100');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ANNISAUL MAHIROH', '2025077101', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077101');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ARINALHAQ FARIDILLAH', '2025077102', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077102');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ATIQOH MINNARIKA RAMADLANI', '2025077103', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077103');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'AULIA SALSA NABILA', '2025077104', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077104');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'BALQIS AYU NUR SHOFIYATUS S', '2025077105', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077105');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'DEA AMALIA', '2025077106', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077106');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'DECHA FAHRISATUN NAJAH', '2025077107', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077107');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'DWI ALISIN CHERYL', '2025077108', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077108');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ENJEL ANGGI ANGGRAENI', '2025077109', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077109');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'INDANA ZULFA KHODIJAH A.', '2025077110', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077110');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'KHALIDATUN AFRINA AL-AFIQOH', '2025077111', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077111');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'KHANSA NABIIHAH SAKHIH N', '2025077112', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077112');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'LIFI NUR AISYAH', '2025077113', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077113');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'MEDINA KANIA KAMIL', '2025077114', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077114');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'QOTHRUNNADA SYAFA AZ-ZAHRA', '2025077115', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077115');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'SALSA NABILA YUSNIAH', '2025077116', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077116');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'TANIYA DWI LESTARI', '2025077117', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077117');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ZELDA OCTAVIA', '2025077118', 'Perempuan', 14, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077118');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ADIBAH KHOZANATUL AULIYAH', '2025077119', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077119');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ALIF MA''RIFATUS ZAHRAH', '2025077120', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077120');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ALMIRA NURUN NAJWAH', '2025077121', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077121');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'AMIRAH ARDELIA AGETHA', '2025077122', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077122');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ANANTA JIHAN SYAH TSALITSAH', '2025077123', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077123');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ASSSYIFATUL HUSNAH', '2025077124', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077124');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'CLARA WAHYU AULIYAH', '2025077125', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077125');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'DESIYA NASYWA KAMILAH', '2025077126', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077126');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'DIAN ERLY AQNESIA', '2025077127', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077127');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'DINA EL-YASMIN AL-MAHFUDZI', '2025077128', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077128');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'DWI PUTRI AISYAH FARHANAH', '2025077129', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077129');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'FAIZATU ALFIANA NUR RAMADHANI', '2025077130', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077130');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'FARAH NUR AQILAH', '2025077131', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077131');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'FAROKHA INDAH SETIAWATI', '2025077132', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077132');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'HIDAYATUL MAHFIROH', '2025077133', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077133');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'IGNES ZADA SHIDQIYA', '2025077134', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077134');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'KIBZA ILFI NUR DIANA', '2025077135', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077135');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NAFA SAHRIYATUL KHUSNA', '2025077136', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077136');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NAJMA AZALIA MUMTAZUMI', '2025077137', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077137');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NAJWA RIHADATUL ''AISYI', '2025077138', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077138');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NATASYA ADITIYA SALSABILA CHOIRI', '2025077139', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077139');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NATASYA RHEINA ADELLIA', '2025077140', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077140');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NAURAH CALLISTA SALSABILA', '2025077141', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077141');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NAURAH WINDI WULANDARI', '2025077142', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077142');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NUR FAIZZAH QOMARINA', '2025077143', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077143');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'PUTIKHATUL ABWAAB', '2025077144', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077144');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'QIBZA LIFI NURDIANA', '2025077145', 'Perempuan', 15, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077145');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'AFIQAH QUEEN SHOLIHAH', '2025077146', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077146');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ANGGARAINI PUSPITA SARI', '2025077147', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077147');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ANIS NUR FAIZAH', '2025077148', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077148');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ARINA HIDAYATI BILQIS', '2025077149', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077149');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'CINTA AURA', '2025077150', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077150');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'DHAWIYAH USWATUN  HASANNAH', '2025077151', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077151');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'DWI CAHYANI TRI', '2025077152', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077152');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'DYAH MUSTIKA TRIBUANA TUNGGA DEWI', '2025077153', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077153');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'FARA AZ-ZAHRA', '2025077154', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077154');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'FITRI SALMA QURROTAA''YUN', '2025077155', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077155');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'HIKMAH MAULIDAH', '2025077156', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077156');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'JEHAN NUR NAFALINA', '2025077157', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077157');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'KIARA MUKHASSONAH', '2025077158', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077158');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'MAIDINA RAHMA SALSABILA', '2025077159', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077159');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'MEISYA ADHIFATUR ROHMANIYAH', '2025077160', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077160');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NADA SIFAUL QOLBY', '2025077161', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077161');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NAIRAH NIHLATUL ULMAH', '2025077162', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077162');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NALA RAHMAH SALSABILA', '2025077163', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077163');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NIHAYATUN NAJWA', '2025077164', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077164');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'QORY EVANGGELINA AYUMI BILQIS', '2025077165', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077165');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'SALMA SYARIFAH ASSA''UDIYAH', '2025077166', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077166');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'SALSABILA ZAHRA AL-BAYYINAH', '2025077167', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077167');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'SALWA AQROBIN', '2025077168', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077168');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'SHEISYA KANNAH CYBIELLAH DZARAFAT', '2025077169', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077169');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'SHILVA IKFINA HIMMATIN', '2025077170', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077170');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'TASYA LATHIFAH LISTINNAH', '2025077171', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077171');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'TSABITA NURUN NAJWA', '2025077172', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077172');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'TSANIYAH NAILATUL IZZA KHAIRINNISWAH', '2025077173', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077173');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'TUHFATUL WAFIROH', '2025077174', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077174');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ABELIA ZAHRA NATASYAFIRAH', '2025077175', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077175');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'AULIYA VITA RAHMANI', '2025077176', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077176');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'CITRA ATHIROTUL HUBBIYAH', '2025077177', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077177');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'DEWI MARTHA TSABITA', '2025077178', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077178');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'FITRI SALWA QURROTA A', '2025077179', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077179');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'GEA REGINA PUTRI', '2025077180', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077180');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'KHARISMA ALIFATUZZAHRA', '2025077181', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077181');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'KIRANA ARSELIA', '2025077182', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077182');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'MILHATUR RAHMAH WULANDARI', '2025077183', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077183');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NAISYLA AIRIN AZZAHRA', '2025077184', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077184');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NUR FARIHATUL LAILI', '2025077185', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077185');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'NUR MAFAIDHATUN NABILA', '2025077186', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077186');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'RACHEL IMAMATUL KAMILAH', '2025077187', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077187');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'RADIFA RUZANA PUTRI', '2025077188', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077188');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'UMMI LATIFATUS SA''DIYAH', '2025077189', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077189');",
  "INSERT INTO murid (nama, nis, jenis_kelamin, kelas_madin_id, created_at, updated_at) SELECT 'ZIDATUN NAYLA IZZA BILLAH', '2025077190', 'Perempuan', 16, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM murid WHERE nis = '2025077190');"
];

export async function GET() {
  try {
    let executedCount = 0;

    for (const stmt of SQL_STATEMENTS) {
      if (stmt && stmt.length > 5) {
        await pool.execute(stmt);
        executedCount++;
      }
    }

    return NextResponse.json({
      success: true,
      message: 'Migrasi 268 Santri Baru Tadris 2025/2026 BERHASIL SELESAI di Production cPanel!',
      total_query_dieksekusi: executedCount,
      rincian: '78 Santri lama di-update kelas madin-nya, 190 Santri murni baru di-insert ke database.'
    });
  } catch (error: any) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
